# -*- coding: utf-8 -*-
"""
化学纤维数据集 Part 2:
3. 生物基与生物可降解聚合物纤维 (BIO_DEGR)
4. 高性能与特种工程有机纤维 (HIGH_PERF: 芳纶、UHMWPE、刚性杂环、工程塑料、氟聚物、交联耐热)
"""

FIBERS_PART_2 = [
    # ==================== 1. 生物基与可降解脂肪族聚酯纤维 (BIO_ALIPH) ====================
    {
        "category_code": "BIO_ALIPH",
        "code": "PLA",
        "name_zh": "聚乳酸纤维 (PLA/玉米纤维)",
        "name_en": "Polylactic Acid Fiber (PLA)",
        "chemical_name": "聚L-乳酸",
        "chemical_formula": "[-CH(CH3)-COO-]n",
        "cas_number": "26100-51-6",
        "generation": "第3代生物基全降解合成纤维",
        "discovery_year": "1932",
        "commercial_year": "1997",
        "pioneering_entity": "Carothers / Cargill Dow (NatureWorks Ingeo) / 海正生物",
        "spinning_method": "熔融纺丝 (高纯左旋丙交酯开环聚合，熔体挤出牵伸)",
        "density_g_cm3": 1.25,
        "tensile_strength_cn_dtex": 4.2,
        "tensile_strength_gpa": 0.53,
        "tensile_modulus_gpa": 4.5,
        "elongation_at_break_pct": 30.0,
        "moisture_regain_pct": 0.6,
        "loi_pct": 26.0, # 离火自熄、发烟量极小且无毒
        "melting_point_c": 175.0,
        "max_service_temp_c": 110.0,
        "typical_applications": "环保茶包袋、一次性卫生巾面层无纺布、绿色运动时装、可堆肥包装布、汽车内饰顶棚",
        "representative_brands": "Ingeo (NatureWorks), 海正PLA, 丰原生物玉米纤维",
        "tech_status_2026": "百万吨级全产业链贯通，立体复合PDLA/PLLA高耐温(耐热超130℃)技术全面打破传统PLA耐温瓶颈",
        "is_bio_based": 1,
        "is_biodegradable": 1,
        "is_high_performance": 0,
        "aliases": [("玉米纤维", "colloquial"), ("PLA纤维", "abbreviation"), ("Ingeo", "trade_name"), ("PLA", "iso_code")],
        "standards": [("GB", "GB/T 33614-2017", "聚乳酸(PLA)牵伸丝"), ("ISO", "ISO 2076:2021", "PLA generic name")]
    },
    {
        "category_code": "BIO_ALIPH",
        "code": "PHA",
        "name_zh": "聚羟基脂肪酸酯纤维 (PHA/PHBV/P34HB)",
        "name_en": "Polyhydroxyalkanoates Fiber",
        "chemical_name": "微生物发酵合成聚羟基脂肪酸酯",
        "chemical_formula": "[-O-CH(R)-(CH2)x-CO-]n",
        "cas_number": "29434-13-7",
        "generation": "第4代全自然环境降解生物纤维",
        "discovery_year": "1926",
        "commercial_year": "2015",
        "pioneering_entity": "Lemoigne / 蓝晶微生物 (Bluepha) / 微构工场",
        "spinning_method": "熔融纺丝或湿法静电纺 (嗜盐微生物非粮碳源发酵提取聚合物)",
        "density_g_cm3": 1.25,
        "tensile_strength_cn_dtex": 3.0,
        "tensile_strength_gpa": 0.38,
        "tensile_modulus_gpa": 3.5,
        "elongation_at_break_pct": 25.0,
        "moisture_regain_pct": 0.8,
        "loi_pct": 24.0,
        "melting_point_c": 170.0,
        "max_service_temp_c": 100.0,
        "typical_applications": "海洋水体与土壤无痕降解渔网、农用可降解防草地膜、高端医美缝合线、可冲散湿巾",
        "representative_brands": "Bluepha PHA, Kaneka Green Planet, Danimer Nodax",
        "tech_status_2026": "在常温海水环境中几个月内完全降解为水和CO2，成为攻克全球海洋微塑料危机的终极纤维材料",
        "is_bio_based": 1,
        "is_biodegradable": 1,
        "is_high_performance": 0,
        "aliases": [("PHA纤维", "abbreviation"), ("PHBV", "chemical_name"), ("P34HB", "chemical_name")],
        "standards": [("ASTM", "ASTM D6691", "Determining Aerobic Biodegradation of Plastic Materials in the Marine Environment")]
    },
    {
        "category_code": "BIO_ALIPH",
        "code": "PCL",
        "name_zh": "聚己内酯纤维 (PCL纤维)",
        "name_en": "Polycaprolactone Fiber",
        "chemical_name": "聚ε-己内酯",
        "chemical_formula": "[-O-(CH2)5-CO-]n",
        "cas_number": "24980-41-4",
        "generation": "第3代生物医用降解纤维",
        "discovery_year": "1930s",
        "commercial_year": "1980s",
        "pioneering_entity": "Union Carbide (Tone PCL)",
        "spinning_method": "低温熔融纺丝、溶液静电纺丝",
        "density_g_cm3": 1.15,
        "tensile_strength_cn_dtex": 2.6,
        "tensile_strength_gpa": 0.30,
        "tensile_modulus_gpa": 0.5,
        "elongation_at_break_pct": 80.0,
        "moisture_regain_pct": 0.4,
        "loi_pct": 20.0,
        "melting_point_c": 60.0, # 超低熔点热塑性
        "max_service_temp_c": 45.0,
        "typical_applications": "微创低温定型医用矫形支架、缓释药物纳米纤维载体、3D组织工程细胞再生脚手架",
        "representative_brands": "Capa (Ingevity), Monocryl 组分",
        "tech_status_2026": "在组织工程骨软骨再生微支架、神经修复微导管等高端医疗领域形成系列临床标准",
        "is_bio_based": 0,
        "is_biodegradable": 1,
        "is_high_performance": 0,
        "aliases": [("PCL", "abbreviation"), ("聚己内酯", "chemical_name")],
        "standards": [("ASTM", "ASTM F1925", "Standard Specification for Virgin Poly(caprolactone) for Surgical Implants")]
    },
    {
        "category_code": "BIO_ALIPH",
        "code": "PGA",
        "name_zh": "聚乙醇酸纤维 (PGA/聚交酯)",
        "name_en": "Polyglycolic Acid Fiber",
        "chemical_name": "聚羟基乙酸",
        "chemical_formula": "[-O-CH2-CO-]n",
        "cas_number": "26009-03-0",
        "generation": "第3代高强超快吸收生物纤维",
        "discovery_year": "1954",
        "commercial_year": "1970",
        "pioneering_entity": "American Cyanamid (Dexon 德克松外科缝线)",
        "spinning_method": "高真空熔融纺丝与多级热牵伸",
        "density_g_cm3": 1.53,
        "tensile_strength_cn_dtex": 8.0, # 降解聚酯中强度最高
        "tensile_strength_gpa": 1.22,
        "tensile_modulus_gpa": 7.5,
        "elongation_at_break_pct": 18.0,
        "moisture_regain_pct": 0.5,
        "loi_pct": 28.0,
        "melting_point_c": 225.0,
        "max_service_temp_c": 120.0,
        "typical_applications": "外科可吸收手术缝合线(Dexon)、页岩油气深井可溶压裂暂堵球与桥塞工具、可降解血管支架",
        "representative_brands": "Dexon, Kureha PGA, 国能神华包头煤制PGA",
        "tech_status_2026": "万吨级煤化工草酸二甲酯路线PGA规模投产，石油工程深井完井工具与高端医疗缝合线实现全面替代",
        "is_bio_based": 0,
        "is_biodegradable": 1,
        "is_high_performance": 1,
        "aliases": [("PGA", "abbreviation"), ("聚羟基乙酸", "chemical_name"), ("Dexon", "trade_name")],
        "standards": [("YY", "YY 1116-2020", "可吸收外科缝线")]
    },
    {
        "category_code": "BIO_ALIPH",
        "code": "PLGA",
        "name_zh": "聚(L-丙交酯-共-乙交酯)纤维 (PLGA)",
        "name_en": "Poly(L-lactide-co-glycolide) Fiber",
        "chemical_name": "L-丙交酯与乙交酯无规/嵌段共聚物",
        "chemical_formula": "[-CH(CH3)COO-]x-[-CH2COO-]y",
        "cas_number": "26780-50-7",
        "generation": "第3代精准调控医用降解纤维",
        "discovery_year": "1970s",
        "commercial_year": "1974",
        "pioneering_entity": "Ethicon (强生 Vicryl / 薇乔线)",
        "spinning_method": "精密熔融纺丝或静电纺丝",
        "density_g_cm3": 1.35,
        "tensile_strength_cn_dtex": 6.8,
        "tensile_strength_gpa": 0.92,
        "tensile_modulus_gpa": 6.0,
        "elongation_at_break_pct": 22.0,
        "moisture_regain_pct": 0.5,
        "loi_pct": 26.0,
        "melting_point_c": 200.0,
        "max_service_temp_c": 110.0,
        "typical_applications": "强生Vicryl可吸收缝合线、可控体内吸收组织补片、靶向长效抗癌药物纳米缓释微纤",
        "representative_brands": "Vicryl (薇乔), Polyglactin 910",
        "tech_status_2026": "通过调控单体比例可精准设定体内降解周期(2周至6个月)，保持临床外科缝线全球金标准",
        "is_bio_based": 0,
        "is_biodegradable": 1,
        "is_high_performance": 1,
        "aliases": [("PLGA", "abbreviation"), ("Vicryl", "trade_name"), ("薇乔", "trade_name")],
        "standards": [("ASTM", "ASTM F1926", "Standard Test Method for Dissolution of Biodegradable Polymeric Materials")]
    },
    {
        "category_code": "BIO_ALIPH",
        "code": "PDO",
        "name_zh": "聚对二氧环己酮纤维 (PDS/PDO线)",
        "name_en": "Polydioxanone Fiber",
        "chemical_name": "聚(1,4-二氧杂环己烷-2-酮)",
        "chemical_formula": "[-O-(CH2)2-O-CH2-CO-]n",
        "cas_number": "29964-84-9",
        "generation": "第3代单丝高韧医用生物纤维",
        "discovery_year": "1970s",
        "commercial_year": "1981",
        "pioneering_entity": "Ethicon (DuPont/强生 PDS)",
        "spinning_method": "熔融纺丝与连续固相退火单丝挤出",
        "density_g_cm3": 1.38,
        "tensile_strength_cn_dtex": 5.2,
        "tensile_strength_gpa": 0.72,
        "tensile_modulus_gpa": 2.2,
        "elongation_at_break_pct": 35.0,
        "moisture_regain_pct": 0.4,
        "loi_pct": 22.0,
        "melting_point_c": 110.0,
        "max_service_temp_c": 75.0,
        "typical_applications": "医美微创面部抗衰倒刺提升线(大V线)、小儿心血管长效可吸收手术单丝、防粘连疝气修补网",
        "representative_brands": "PDS II (强生), 恒生PPDO提拉线",
        "tech_status_2026": "在医疗美容微创埋线提升与儿童心胸外科手术中为无可争议的刚性标杆单丝材料",
        "is_bio_based": 0,
        "is_biodegradable": 1,
        "is_high_performance": 1,
        "aliases": [("PDS", "trade_name"), ("PDO", "abbreviation"), ("PPDO", "abbreviation"), ("快翎线", "colloquial")],
        "standards": [("YY", "YY 1116-2020", "可吸收单丝外科缝线标准")]
    },
    {
        "category_code": "BIO_ALIPH",
        "code": "PBS",
        "name_zh": "聚丁二酸丁二醇酯纤维 (PBS/PBAT共聚酯纤维)",
        "name_en": "Poly(butylene succinate) & PBAT Fibers",
        "chemical_name": "聚丁二酸-1,4-丁二醇酯",
        "chemical_formula": "[-O-(CH2)4-O-CO-(CH2)2-CO-]n",
        "cas_number": "25777-14-4",
        "generation": "第3代热塑性降解共聚酯纤维",
        "discovery_year": "1990s",
        "commercial_year": "2000s",
        "pioneering_entity": "昭和高分子 (Bionolle) / 金发科技",
        "spinning_method": "熔融纺丝 (常规熔纺与纺粘无纺布工艺)",
        "density_g_cm3": 1.26,
        "tensile_strength_cn_dtex": 3.2,
        "tensile_strength_gpa": 0.40,
        "tensile_modulus_gpa": 2.0,
        "elongation_at_break_pct": 45.0,
        "moisture_regain_pct": 0.7,
        "loi_pct": 21.0,
        "melting_point_c": 115.0,
        "max_service_temp_c": 85.0,
        "typical_applications": "农业全生物降解育苗钵、水土保持绿化防护网、一次性酒店日用品织物、包装填充棉",
        "representative_brands": "Bionolle, Ecoflex (BASF), 金发PBS",
        "tech_status_2026": "柔韧性大幅优于纯PLA，与PLA共混复合熔融纺丝制备兼具刚韧性能的全降解无纺布",
        "is_bio_based": 0,
        "is_biodegradable": 1,
        "is_high_performance": 0,
        "aliases": [("PBS纤维", "abbreviation"), ("PBAT纤维", "abbreviation"), ("Bionolle", "trade_name")],
        "standards": [("GB", "GB/T 32366-2015", "生物降解聚丁二酸丁二醇酯(PBS)")]
    },

    # ==================== 2. 新型生物基呋喃二甲酸聚酯 (BIO_FDCA) ====================
    {
        "category_code": "BIO_FDCA",
        "code": "PEF",
        "name_zh": "聚呋喃二甲酸乙二醇酯纤维 (PEF/全生物基芳香族聚酯)",
        "name_en": "Polyethylene Furanoate Fiber (PEF)",
        "chemical_name": "聚2,5-呋喃二甲酸乙二醇酯",
        "chemical_formula": "[-CO-(C4H2O)-CO-O-(CH2)2-O-]n",
        "cas_number": "28728-19-0",
        "generation": "第4代全生物基划时代聚酯",
        "discovery_year": "2009",
        "commercial_year": "2024",
        "pioneering_entity": "Avantium (荷商阿凡提亚) / 中科院宁波材料所",
        "spinning_method": "熔体缩聚-固相增粘-高速熔融纺丝",
        "density_g_cm3": 1.43,
        "tensile_strength_cn_dtex": 5.8,
        "tensile_strength_gpa": 0.83,
        "tensile_modulus_gpa": 14.5, # 模量与刚性显著超越PET涤纶
        "elongation_at_break_pct": 18.0,
        "moisture_regain_pct": 0.7,
        "loi_pct": 24.0,
        "melting_point_c": 215.0,
        "max_service_temp_c": 140.0,
        "typical_applications": "高阻隔绿色工业滤布、全生物基耐蠕变轮胎帘线、高性能防紫外防风运动风衣、阻气特种织物",
        "representative_brands": "Releaf, Avantium PEF",
        "tech_status_2026": "万吨级工业化旗舰装置平稳运行，阻气性较PET提升10倍，碳足迹减少70%以上，被誉为‘绿色PET杀手’",
        "is_bio_based": 1,
        "is_biodegradable": 0,
        "is_high_performance": 1,
        "aliases": [("PEF", "abbreviation"), ("呋喃聚酯", "colloquial"), ("生物基PEF", "standard_name")],
        "standards": [("ASTM", "ASTM D6866", "Standard Test Methods for Determining Biobased Content")]
    },

    # ==================== 3. 芳香族聚酰胺特种纤维 (HP_ARAMID) ====================
    {
        "category_code": "HP_ARAMID",
        "code": "PPTA",
        "name_zh": "对位芳纶 (芳纶1414/凯夫拉)",
        "name_en": "Para-Aramid Fiber (PPTA)",
        "chemical_name": "聚对苯二甲酰对苯二胺",
        "chemical_formula": "[-NH-C6H4-NH-CO-C6H4-CO-]n",
        "cas_number": "26125-61-1",
        "generation": "第3代战略高性能特种纤维",
        "discovery_year": "1965",
        "commercial_year": "1971",
        "pioneering_entity": "Stephanie Kwolek (斯蒂芬妮·克沃勒克 / 杜邦 DuPont Kevlar)",
        "spinning_method": "液晶干喷湿纺 (浓硫酸发烟液晶相溶液喷丝，水浴骤冷牵伸热定型)",
        "density_g_cm3": 1.44,
        "tensile_strength_cn_dtex": 22.0,
        "tensile_strength_gpa": 3.16,
        "tensile_modulus_gpa": 110.0, # 极高拉伸模量，比钢丝高出数倍
        "elongation_at_break_pct": 3.5,
        "moisture_regain_pct": 4.5,
        "loi_pct": 29.0, # 离火自熄、遇高温炭化不熔滴
        "melting_point_c": None, # 无熔点，560℃高温分解
        "max_service_temp_c": 260.0,
        "typical_applications": "军警防弹衣与战术头盔、光纤中心加强芯抗拉纱、航天发动机防碎弹道护罩、高端防刺防割手套",
        "representative_brands": "Kevlar (杜邦凯夫拉), Twaron (帝人芳纶), 泰和新材泰普龙",
        "tech_status_2026": "超高强高模型(Kevlar 129/Twaron 2200)全国产化完全自主可控，年产能破3万吨位居全球前列",
        "is_bio_based": 0,
        "is_biodegradable": 0,
        "is_high_performance": 1,
        "aliases": [("芳纶1414", "colloquial"), ("对位芳纶", "standard_name"), ("Kevlar", "trade_name"), ("Twaron", "trade_name"), ("凯夫拉", "trade_name"), ("PPTA", "abbreviation")],
        "standards": [("GB", "GB/T 31888-2015", "对位芳香族聚酰胺长丝"), ("ISO", "ISO 2076:2021", "Aramid")]
    },
    {
        "category_code": "HP_ARAMID",
        "code": "PMIA",
        "name_zh": "间位芳纶 (芳纶1313/诺梅克斯)",
        "name_en": "Meta-Aramid Fiber (PMIA)",
        "chemical_name": "聚间苯二甲酰间苯二胺",
        "chemical_formula": "[-NH-C6H4-NH-CO-C6H4-CO-]n",
        "cas_number": "25765-47-3",
        "generation": "第3代耐高温耐火焰特种纤维",
        "discovery_year": "1961",
        "commercial_year": "1967",
        "pioneering_entity": "DuPont (杜邦 Nomex / 诺梅克斯)",
        "spinning_method": "低温溶液湿法纺丝或干法纺丝 (DMAc-LiCl溶剂体系)",
        "density_g_cm3": 1.38,
        "tensile_strength_cn_dtex": 4.8,
        "tensile_strength_gpa": 0.66,
        "tensile_modulus_gpa": 12.0,
        "elongation_at_break_pct": 30.0,
        "moisture_regain_pct": 5.5,
        "loi_pct": 32.0, # 卓越耐火性
        "melting_point_c": None, # 400℃热裂解
        "max_service_temp_c": 220.0,
        "typical_applications": "特勤消防战斗服、赛车手抗火服、飞机客舱内饰阻燃壁板、特高压变压器芳纶绝缘纸(Nomex纸)",
        "representative_brands": "Nomex (诺梅克斯), Conex (帝人), 美士达 (泰和新材)",
        "tech_status_2026": "原液着色耐光老化间位芳纶与航空级芳纶蜂窝芯材纸基材料彻底实现自主技术全覆盖",
        "is_bio_based": 0,
        "is_biodegradable": 0,
        "is_high_performance": 1,
        "aliases": [("芳纶1313", "colloquial"), ("间位芳纶", "standard_name"), ("Nomex", "trade_name"), ("诺梅克斯", "trade_name"), ("PMIA", "abbreviation")],
        "standards": [("GB", "GB/T 31889-2015", "间位芳香族聚酰胺短纤维"), ("ISO", "ISO 2076:2021", "Aramid")]
    },
    {
        "category_code": "HP_ARAMID",
        "code": "ARAMID-III",
        "name_zh": "杂环芳纶 (芳纶III / Armos / Rusar)",
        "name_en": "Heterocyclic Aramid Fiber (Aramid III)",
        "chemical_name": "共聚苯并咪唑芳香族聚酰胺",
        "chemical_formula": "Copoly(diaminophenyl-benzimidazole-terephthalamide)",
        "cas_number": None,
        "generation": "第4代超高强抗弹特种纤维",
        "discovery_year": "1970s",
        "commercial_year": "1985",
        "pioneering_entity": "俄罗斯前苏联全俄人造纤维研究院 (VNIISV / Armos, Rusar) / 中蓝晨光",
        "spinning_method": "干喷湿纺或湿法纺丝 (含苯并咪唑刚性单体共聚，液晶相纺丝)",
        "density_g_cm3": 1.45,
        "tensile_strength_cn_dtex": 28.0,
        "tensile_strength_gpa": 4.10, # 强度大幅超越传统PPTA
        "tensile_modulus_gpa": 135.0,
        "elongation_at_break_pct": 3.0,
        "moisture_regain_pct": 3.8,
        "loi_pct": 38.0,
        "melting_point_c": None, # 550℃分解
        "max_service_temp_c": 300.0,
        "typical_applications": "战略导弹固体火箭发动机缠绕壳体、高超音速飞行器结构件、重型顶级防弹装甲、极端宇航缆绳",
        "representative_brands": "Rusar-S, Armos, 中蓝晨光芳纶III",
        "tech_status_2026": "我国在杂环单体合成及连续干喷湿纺工程化取得重大突破，实现宇航主承力结构批量列装",
        "is_bio_based": 0,
        "is_biodegradable": 0,
        "is_high_performance": 1,
        "aliases": [("芳纶III", "colloquial"), ("杂环芳香聚酰胺", "standard_name"), ("Armos", "trade_name"), ("Rusar", "trade_name")],
        "standards": [("GB", "GB/T 36768-2018", "超高分子量杂环芳香族聚酰胺长丝")]
    },
    {
        "category_code": "HP_ARAMID",
        "code": "PSA",
        "name_zh": "聚砜酰胺纤维 (芳砜纶 / PSA纤维)",
        "name_en": "Polysulfonamide Fiber (PSA)",
        "chemical_name": "聚对苯二甲酰-3,3'-二氨基二苯砜",
        "chemical_formula": "[-NH-C6H4-SO2-C6H4-NH-CO-C6H4-CO-]n",
        "cas_number": "31843-05-9",
        "generation": "第3代中国独创耐温阻燃芳香纤维",
        "discovery_year": "1972",
        "commercial_year": "1980s",
        "pioneering_entity": "上海合成纤维研究所 (中国原创重大突破)",
        "spinning_method": "低温溶液湿法纺丝",
        "density_g_cm3": 1.40,
        "tensile_strength_cn_dtex": 3.8,
        "tensile_strength_gpa": 0.53,
        "tensile_modulus_gpa": 9.5,
        "elongation_at_break_pct": 18.0,
        "moisture_regain_pct": 4.5,
        "loi_pct": 33.0, # 天然优异阻燃，不融滴发烟极少
        "melting_point_c": None, # 420℃开始热降解
        "max_service_temp_c": 250.0,
        "typical_applications": "250℃工业袋式除尘滤料、冶炼焊接防飞溅工服、特种电机H级电气绝缘纸、防火隔热毡",
        "representative_brands": "Tanlon (芳砜纶 / 上纤所)",
        "tech_status_2026": "具有完全自主知识产权，在电力绝缘、钢铁水泥高温尾气治理滤袋保持长期竞争优势",
        "is_bio_based": 0,
        "is_biodegradable": 0,
        "is_high_performance": 1,
        "aliases": [("芳砜纶", "colloquial"), ("PSA纤维", "abbreviation"), ("Tanlon", "trade_name")],
        "standards": [("GB", "FZ/T 52011-2019", "聚砜酰胺短纤维")]
    },
    {
        "category_code": "HP_ARAMID",
        "code": "TECHNORA",
        "name_zh": "共聚对位芳纶纤维 (Technora / 泰诺拉)",
        "name_en": "Co-Polyparaphenylene Terephthalamide (Technora)",
        "chemical_name": "对苯二甲酰氯与对苯二胺/3,4'-二氨基二苯醚三元共聚物",
        "chemical_formula": "PPTA-co-ODA copolymer",
        "cas_number": "63428-84-2",
        "generation": "第3代高韧共聚芳香纤维",
        "discovery_year": "1974",
        "commercial_year": "1987",
        "pioneering_entity": "Teijin (日本帝人)",
        "spinning_method": "各向同性溶液干喷湿纺及超高倍热拉伸 (热拉伸比可达10倍)",
        "density_g_cm3": 1.39,
        "tensile_strength_cn_dtex": 24.5,
        "tensile_strength_gpa": 3.40,
        "tensile_modulus_gpa": 74.0, # 模量适中但断裂延伸率更高，耐疲劳极佳
        "elongation_at_break_pct": 4.6,
        "moisture_regain_pct": 2.2,
        "loi_pct": 25.0,
        "melting_point_c": None, # 500℃热分解
        "max_service_temp_c": 210.0,
        "typical_applications": "深海系泊缆绳、汽车高应力正时皮带骨架、耐屈挠输送带、航空降落伞吊绳",
        "representative_brands": "Technora (泰诺拉 / Teijin)",
        "tech_status_2026": "在反复屈折耐疲劳寿命上超越标准Kevlar数倍，为重载动负荷绳缆首选特种芳纶",
        "is_bio_based": 0,
        "is_biodegradable": 0,
        "is_high_performance": 1,
        "aliases": [("Technora", "trade_name"), ("泰诺拉", "trade_name"), ("共聚芳纶", "colloquial")],
        "standards": [("ISO", "ISO 2076:2021", "Aramid")]
    },

    # ==================== 4. 超高分子量聚乙烯纤维 (HP_UHMWPE) ====================
    {
        "category_code": "HP_UHMWPE",
        "code": "UHMWPE",
        "name_zh": "超高分子量聚乙烯纤维 (迪尼玛/大力马/防弹纤维)",
        "name_en": "Ultra-High Molecular Weight Polyethylene Fiber",
        "chemical_name": "超高分子量聚乙烯 (重均分子量>300万-500万)",
        "chemical_formula": "[-CH2-CH2-]n (MW > 3,000,000)",
        "cas_number": "9002-88-4",
        "generation": "第3代世界三大高性能纤维之一",
        "discovery_year": "1963",
        "commercial_year": "1979",
        "pioneering_entity": "Piet Lemstra (帝斯曼 DSM Dyneema) / AlliedSignal (Spectra)",
        "spinning_method": "冻胶凝胶纺丝-超高倍热拉伸 (十氢萘或白油溶剂制备超缠结解聚冻胶，拉伸比>30-50倍)",
        "density_g_cm3": 0.97, # 密度低于水，可在水面漂浮的高性能纤维
        "tensile_strength_cn_dtex": 36.0,
        "tensile_strength_gpa": 3.50, # 比强度是优质钢材的15倍
        "tensile_modulus_gpa": 120.0,
        "elongation_at_break_pct": 3.2,
        "moisture_regain_pct": 0.01,
        "loi_pct": 17.0, # 唯一短板：易燃
        "melting_point_c": 150.0,
        "max_service_temp_c": 80.0, # 长期受热易蠕变
        "typical_applications": "超轻防弹插板、防切割五级手套、深海拖缆系泊巨绳、超轻高端鱼线、雷达天线罩",
        "representative_brands": "Dyneema (迪尼玛 / Avient), Spectra (霍尼韦尔), 同益中, 九九久",
        "tech_status_2026": "低蠕变超耐磨改性(耐蠕变提升300%)及环保水相干法冻胶纺丝技术彻底工业化，中国产能占全球70%以上",
        "is_bio_based": 0,
        "is_biodegradable": 0,
        "is_high_performance": 1,
        "aliases": [("UHMWPE", "abbreviation"), ("大力马", "colloquial"), ("迪尼玛", "trade_name"), ("Dyneema", "trade_name"), ("Spectra", "trade_name"), ("高强PE", "colloquial")],
        "standards": [("GB", "GB/T 19975-2015", "超高分子量聚乙烯长丝"), ("ISO", "ISO 2076:2021", "Polyethylene high tenacity")]
    },

    # ==================== 5. 刚性链杂环与液晶特种纤维 (HP_HETERO) ====================
    {
        "category_code": "HP_HETERO",
        "code": "PBO",
        "name_zh": "聚苯并双恶唑纤维 (PBO纤维/柴隆)",
        "name_en": "Poly-p-phenylenebenzobisoxazole Fiber (PBO)",
        "chemical_name": "聚(对亚苯基苯并二恶唑)",
        "chemical_formula": "[-C14H6N2O2-]n",
        "cas_number": "62061-07-2",
        "generation": "第4代‘21世纪超级纤维’",
        "discovery_year": "1980s",
        "commercial_year": "1998",
        "pioneering_entity": "美国空军材料实验室 (AFML) / 日本东洋纺 (Toyobo Zylon)",
        "spinning_method": "液晶相干喷湿纺 (多聚磷酸PPA溶液中合成液晶，骤冷凝固水洗热处理)",
        "density_g_cm3": 1.56,
        "tensile_strength_cn_dtex": 42.0,
        "tensile_strength_gpa": 5.80, # 有机纤维断裂强度之冠
        "tensile_modulus_gpa": 280.0, # 模量超越碳纤维标准模量
        "elongation_at_break_pct": 2.5,
        "moisture_regain_pct": 0.6,
        "loi_pct": 68.0, # 极端难燃自熄
        "melting_point_c": None, # 650℃热分解
        "max_service_temp_c": 350.0,
        "typical_applications": "航天隔热层遮阳网、F1赛车驾驶舱防护、火星着陆器减速伞牵引索、高端防暴头盔盾牌",
        "representative_brands": "Zylon (柴隆 / 东洋纺 Toyobo), 中蓝晨光PBO",
        "tech_status_2026": "攻克其固有光紫外老化痛点（纳米表面涂层改性与共聚改性），千吨级高纯连续丝束自主量产稳定供货",
        "is_bio_based": 0,
        "is_biodegradable": 0,
        "is_high_performance": 1,
        "aliases": [("PBO", "abbreviation"), ("Zylon", "trade_name"), ("柴隆", "trade_name"), ("超级纤维", "colloquial")],
        "standards": [("GB", "GB/T 36767-2018", "聚苯并双噁唑长丝")]
    },
    {
        "category_code": "HP_HETERO",
        "code": "PBI",
        "name_zh": "聚苯并咪唑纤维 (PBI纤维)",
        "name_en": "Polybenzimidazole Fiber (PBI)",
        "chemical_name": "聚-2,2'-(间亚苯基)-5,5'-联苯并咪唑",
        "chemical_formula": "[-C20H12N4-]n",
        "cas_number": "25734-65-0",
        "generation": "第3代极限耐火阻燃特种纤维",
        "discovery_year": "1961",
        "commercial_year": "1983",
        "pioneering_entity": "Carl Marvel / Celanese (塞拉尼斯 PBI Products)",
        "spinning_method": "干法纺丝 (DMAc高压溶解挤入高温甬道，随后高温高倍拉伸并磺化稳定)",
        "density_g_cm3": 1.43,
        "tensile_strength_cn_dtex": 3.5,
        "tensile_strength_gpa": 0.50,
        "tensile_modulus_gpa": 6.5,
        "elongation_at_break_pct": 28.0,
        "moisture_regain_pct": 15.0, # 虽为合成纤维，吸湿性极高、穿戴体感极佳
        "loi_pct": 42.0, # 在纯氧中亦难持续燃烧
        "melting_point_c": None, # 超越700℃炭化不溶滴
        "max_service_temp_c": 350.0,
        "typical_applications": "NASA航天服外层耐火面料、高级重型特勤消防外勤战斗服、石化火灾避险防爆服",
        "representative_brands": "PBI (Celazole / PBI Performance Products)",
        "tech_status_2026": "国际最高级别热防护服装不可替代标配；与对位芳纶按比例混纺织物占据全球高端消防核心地位",
        "is_bio_based": 0,
        "is_biodegradable": 0,
        "is_high_performance": 1,
        "aliases": [("PBI", "abbreviation"), ("聚苯并咪唑", "chemical_name"), ("Celazole", "trade_name")],
        "standards": [("ISO", "ISO 2076:2021", "Polybenzimidazole generic name")]
    },
    {
        "category_code": "HP_HETERO",
        "code": "PIPD",
        "name_zh": "聚二咪唑并吡啶撑二羟基亚苯基纤维 (M5纤维)",
        "name_en": "Poly(2,6-diimidazo[4,5-b:4',5'-e]pyridinylene-1,4-(2,5-dihydroxy)phenylene) (M5)",
        "chemical_name": "双羟基吡啶并二咪唑聚合物 (具有网状双分子内氢键刚性棒状分子)",
        "chemical_formula": "PIPD Polymer",
        "cas_number": None,
        "generation": "第4代超高压缩强度刚性链纤维",
        "discovery_year": "1990s",
        "commercial_year": "2000s",
        "pioneering_entity": "Akzo Nobel / Magellan Systems International",
        "spinning_method": "液晶相干喷湿纺 (浓PPA溶剂水解凝胶，多重分子链间双氢键致密排列)",
        "density_g_cm3": 1.70,
        "tensile_strength_cn_dtex": 35.0,
        "tensile_strength_gpa": 5.0,
        "tensile_modulus_gpa": 330.0, # 模量逼近超高模量碳纤维
        "elongation_at_break_pct": 1.5,
        "moisture_regain_pct": 1.0,
        "loi_pct": 50.0,
        "melting_point_c": None, # >500℃耐温
        "max_service_temp_c": 320.0,
        "typical_applications": "航空航天机翼复合材料桁条、高抗冲击弹道护板、超高压缩复合支架(克服传统碳纤维易脆断压屈痛点)",
        "representative_brands": "M5 Fiber",
        "tech_status_2026": "其轴向抗压缩强度达1.6 GPa（为对位芳纶的3倍），在解决复合材料压缩破坏关键技术中发挥核心作用",
        "is_bio_based": 0,
        "is_biodegradable": 0,
        "is_high_performance": 1,
        "aliases": [("M5纤维", "colloquial"), ("PIPD", "abbreviation")],
        "standards": [("DoD", "MIL-STD Advanced Composite Fibers", "DoD Material Specification")]
    },
    {
        "category_code": "HP_HETERO",
        "code": "TLCP",
        "name_zh": "聚芳酯纤维 (热致液晶高分子纤维 / Vectran)",
        "name_en": "Polyarylate Fiber (Thermotropic Liquid Crystal Polymer / Vectran)",
        "chemical_name": "对羟基苯甲酸与6-羟基-2-萘甲酸无规共聚酯",
        "chemical_formula": "[-O-C6H4-CO-]x-[-O-C10H6-CO-]y",
        "cas_number": "81843-52-9",
        "generation": "第3代热致液晶高性能纤维",
        "discovery_year": "1970s",
        "commercial_year": "1990",
        "pioneering_entity": "Celanese (塞拉尼斯) / Kuraray (日本可乐丽 Vectran)",
        "spinning_method": "熔融纺丝及固相高真空长时后热处理 (熔体直接展现各向异性向列液晶相)",
        "density_g_cm3": 1.40,
        "tensile_strength_cn_dtex": 26.0,
        "tensile_strength_gpa": 3.20,
        "tensile_modulus_gpa": 85.0,
        "elongation_at_break_pct": 3.8,
        "moisture_regain_pct": 0.1, # 极低吸水率
        "loi_pct": 28.0,
        "melting_point_c": 330.0,
        "max_service_temp_c": 160.0,
        "typical_applications": "NASA火星探测器气囊(勇气号/机遇号)、深海超高耐切割系泊绳、羽毛球拍网线、高保真音响振膜",
        "representative_brands": "Vectran (威克特纶 / Kuraray)",
        "tech_status_2026": "在超低温极寒宇航环境下保持超强韧性，且耐弯折疲劳性显著超越碳纤维和芳纶",
        "is_bio_based": 0,
        "is_biodegradable": 0,
        "is_high_performance": 1,
        "aliases": [("Vectran", "trade_name"), ("聚芳酯", "chemical_name"), ("威克特纶", "trade_name"), ("TLCP", "abbreviation")],
        "standards": [("GB", "GB/T 36766-2018", "聚芳酯长丝")]
    },

    # ==================== 6. 特种耐高温工程塑料纤维 (HP_ENG) ====================
    {
        "category_code": "HP_ENG",
        "code": "PPS",
        "name_zh": "聚苯硫醚纤维 (PPS纤维)",
        "name_en": "Polyphenylene Sulfide Fiber (PPS)",
        "chemical_name": "聚(对苯硫醚)",
        "chemical_formula": "[-C6H4-S-]n",
        "cas_number": "25212-74-2",
        "generation": "第3代特种耐酸碱耐温工程纤维",
        "discovery_year": "1967",
        "commercial_year": "1983",
        "pioneering_entity": "Phillips Petroleum (菲利普斯石油 Ryton) / 帝人 / 浙江新和成",
        "spinning_method": "高温熔融纺丝与高倍热牵伸 (熔融温度310℃)",
        "density_g_cm3": 1.35,
        "tensile_strength_cn_dtex": 4.5,
        "tensile_strength_gpa": 0.60,
        "tensile_modulus_gpa": 4.5,
        "elongation_at_break_pct": 25.0,
        "moisture_regain_pct": 0.2,
        "loi_pct": 34.0, # 优良阻燃
        "melting_point_c": 285.0,
        "max_service_temp_c": 190.0,
        "typical_applications": "燃煤火电厂与垃圾焚烧锅炉烟气脱硫除尘高温耐腐蚀滤袋、造纸工业干燥成型网、特种电绝缘织物",
        "representative_brands": "Ryton, Toray PPS, 新和成PPS短纤",
        "tech_status_2026": "在190℃含酸性二氧化硫湿热烟气环境下服役寿命超3年，为我国超低排放环保滤料支柱品种",
        "is_bio_based": 0,
        "is_biodegradable": 0,
        "is_high_performance": 1,
        "aliases": [("PPS", "abbreviation"), ("聚苯硫醚", "chemical_name"), ("Ryton", "trade_name")],
        "standards": [("GB", "GB/T 31890-2015", "聚苯硫醚短纤维"), ("ISO", "ISO 2076:2021", "Polyphenylene sulphide")]
    },
    {
        "category_code": "HP_ENG",
        "code": "PEEK",
        "name_zh": "聚醚醚酮纤维 (PEEK纤维)",
        "name_en": "Polyetheretherketone Fiber (PEEK)",
        "chemical_name": "聚芳醚醚酮",
        "chemical_formula": "[-O-C6H4-O-C6H4-CO-C6H4-]n",
        "cas_number": "29658-26-2",
        "generation": "第3代超耐热宇航工程特种纤维",
        "discovery_year": "1977",
        "commercial_year": "1980s",
        "pioneering_entity": "ICI (英国帝国化学 / Victrex 威格斯) / 中研股份",
        "spinning_method": "超高温熔融纺丝 (熔体温度达380-400℃，需特种抗氧化喷丝组件)",
        "density_g_cm3": 1.30,
        "tensile_strength_cn_dtex": 6.5,
        "tensile_strength_gpa": 0.85,
        "tensile_modulus_gpa": 8.0,
        "elongation_at_break_pct": 20.0,
        "moisture_regain_pct": 0.2,
        "loi_pct": 35.0,
        "melting_point_c": 343.0,
        "max_service_temp_c": 250.0,
        "typical_applications": "航空航天热塑性热熔预浸料基体、网状植入医用脱垂修补片、半导体晶圆烘烤清洗载具网、油井电缆铠装护套",
        "representative_brands": "Zyex (Victrex), PEEK filament, 吉大特塑",
        "tech_status_2026": "热塑性碳纤维/PEEK共混编织预浸料在下一代宽体客机机身壁板制造中进入规模化适航认证",
        "is_bio_based": 0,
        "is_biodegradable": 0,
        "is_high_performance": 1,
        "aliases": [("PEEK", "abbreviation"), ("聚醚醚酮", "chemical_name"), ("Zyex", "trade_name")],
        "standards": [("GB", "GB/T 33616-2017", "聚醚醚酮(PEEK)牵伸丝")]
    },
    {
        "category_code": "HP_ENG",
        "code": "PI-F",
        "name_zh": "聚酰亚胺纤维 (PI纤维)",
        "name_en": "Polyimide Fiber",
        "chemical_name": "聚均苯四甲酰亚胺 / 聚联苯型共聚聚酰亚胺",
        "chemical_formula": "[-N(CO)2C6H2(CO)2N-R-]n",
        "cas_number": "25038-81-7",
        "generation": "第3代全能型耐高温特种纤维",
        "discovery_year": "1960s",
        "commercial_year": "1980s",
        "pioneering_entity": "Evonik (P84 奥地利赢创) / 长春应化所 / 江苏奥神",
        "spinning_method": "湿法或干法两步法纺丝 (聚酰胺酸PAA溶液纺丝后高温化学或热亚胺化)",
        "density_g_cm3": 1.41,
        "tensile_strength_cn_dtex": 5.5,
        "tensile_strength_gpa": 0.80,
        "tensile_modulus_gpa": 12.0, # 高强高模级可达4.0 GPa / 120 GPa
        "elongation_at_break_pct": 16.0,
        "moisture_regain_pct": 2.5,
        "loi_pct": 38.0,
        "melting_point_c": None, # 560℃高温炭化
        "max_service_temp_c": 260.0,
        "typical_applications": "260℃耐温微细异形截面高温除尘滤袋(P84叶裂形)、航天器多层隔热组件(MLI)、航天服阻燃内衬",
        "representative_brands": "P84 (赢创 Evonik), 奥神PI短纤, 惠生PI长丝",
        "tech_status_2026": "高强高模型聚酰亚胺长丝在深空探测器耐辐照绳索和柔性太阳翼薄膜基底增强中实现不可替代应用",
        "is_bio_based": 0,
        "is_biodegradable": 0,
        "is_high_performance": 1,
        "aliases": [("PI纤维", "abbreviation"), ("P84", "trade_name"), ("聚酰亚胺", "chemical_name")],
        "standards": [("GB", "GB/T 31891-2015", "聚酰亚胺短纤维"), ("ISO", "ISO 2076:2021", "Polyimide")]
    },

    # ==================== 7. 含氟聚合物特种纤维 (HP_FLUORO) ====================
    {
        "category_code": "HP_FLUORO",
        "code": "PTFE-F",
        "name_zh": "聚四氟乙烯纤维 (PTFE纤维/氟纶)",
        "name_en": "Polytetrafluoroethylene Fiber (Fluorofibre)",
        "chemical_name": "聚四氟乙烯 (塑料王纤维化)",
        "chemical_formula": "[-CF2-CF2-]n",
        "cas_number": "9002-84-0",
        "generation": "第3代极限耐化学腐蚀特种纤维",
        "discovery_year": "1938",
        "commercial_year": "1953",
        "pioneering_entity": "Roy Plunkett (杜邦 DuPont Teflon / 特氟龙)",
        "spinning_method": "糊状挤出膜裂纺丝法、乳液载体湿纺法 (与纤维素共混烧结炭化载体)",
        "density_g_cm3": 2.15, # 极高密度有机纤维
        "tensile_strength_cn_dtex": 2.5,
        "tensile_strength_gpa": 0.54,
        "tensile_modulus_gpa": 3.0,
        "elongation_at_break_pct": 25.0,
        "moisture_regain_pct": 0.0, # 绝对疏水，吸水率为0
        "loi_pct": 95.0, # 几乎不可燃
        "melting_point_c": 327.0,
        "max_service_temp_c": 260.0,
        "typical_applications": "王水及全溶剂耐极端腐蚀工业密封填料盘根、化工苛刻高温酸洗脱硫滤布、人造心血管微孔移植物(ePTFE)",
        "representative_brands": "Teflon (特氟龙), Gore-Tex (戈尔), Profilen",
        "tech_status_2026": "膜裂纤维及超细微孔膨体ePTFE技术高度成熟，在严苛湿化学催化过滤与人工脏器中持续占据霸主地位",
        "is_bio_based": 0,
        "is_biodegradable": 0,
        "is_high_performance": 1,
        "aliases": [("PTFE纤维", "abbreviation"), ("特氟龙纤维", "trade_name"), ("氟纶", "colloquial"), ("Teflon", "trade_name"), ("FLR", "iso_code")],
        "standards": [("GB", "GB/T 31892-2015", "聚四氟乙烯长丝"), ("ISO", "ISO 2076:2021", "Fluorofibre")]
    },
    {
        "category_code": "HP_FLUORO",
        "code": "PVDF-F",
        "name_zh": "聚偏二氟乙烯纤维 (PVDF纤维)",
        "name_en": "Polyvinylidene Fluoride Fiber",
        "chemical_name": "聚偏氟乙烯 (具有特异电活性β相偶极排列)",
        "chemical_formula": "[-CH2-CF2-]n",
        "cas_number": "24937-79-9",
        "generation": "第3代压电与耐候功能纤维",
        "discovery_year": "1940s",
        "commercial_year": "1970s",
        "pioneering_entity": "Pennwalt (Kynar) / 阿科玛 (Arkema)",
        "spinning_method": "熔融纺丝高倍电场牵伸，或静电纺丝直接原位极化取向诱导β相",
        "density_g_cm3": 1.78,
        "tensile_strength_cn_dtex": 3.5,
        "tensile_strength_gpa": 0.62,
        "tensile_modulus_gpa": 2.5,
        "elongation_at_break_pct": 30.0,
        "moisture_regain_pct": 0.04,
        "loi_pct": 44.0,
        "melting_point_c": 175.0,
        "max_service_temp_c": 140.0,
        "typical_applications": "自供电压电织物传感器、深海隐蔽水听器声学敏感织物、海水淡化微滤中空纤维膜、耐高光耐候特种渔线",
        "representative_brands": "Kynar (阿科玛), Solef (索尔维), 氟碳鱼线",
        "tech_status_2026": "原位极化纳米纤维微纳阵列实现足底与关节运动微能量高效收集，成为柔性可穿戴自驱动主流能量捕获元件",
        "is_bio_based": 0,
        "is_biodegradable": 0,
        "is_high_performance": 1,
        "aliases": [("PVDF", "abbreviation"), ("聚偏氟乙烯", "chemical_name"), ("Kynar", "trade_name"), ("氟碳线", "colloquial")],
        "standards": [("ASTM", "ASTM D3222", "Standard Specification for Unmodified PVDF")]
    },

    # ==================== 8. 耐高温交联热固性纤维 (HP_THERMO) ====================
    {
        "category_code": "HP_THERMO",
        "code": "NOV",
        "name_zh": "酚醛纤维 (诺沃洛伊德/Kynol)",
        "name_en": "Novoloid Fiber (Phenol-Formaldehyde Fiber)",
        "chemical_name": "热固性交联线型酚醛树脂纤维",
        "chemical_formula": "Cross-linked Novolac network",
        "cas_number": "26023-27-8",
        "generation": "第2代特种三维交联耐火耐炭化纤维",
        "discovery_year": "1969",
        "commercial_year": "1972",
        "pioneering_entity": "Carborundum (卡波伦登) / 日本群荣化学 (Gun Ei Chemical)",
        "spinning_method": "热塑性线型酚醛树脂熔融纺丝后，在甲醛与盐酸水溶液中加热固化深度交联",
        "density_g_cm3": 1.27,
        "tensile_strength_cn_dtex": 1.8,
        "tensile_strength_gpa": 0.23,
        "tensile_modulus_gpa": 4.5,
        "elongation_at_break_pct": 30.0,
        "moisture_regain_pct": 6.0,
        "loi_pct": 34.0, # 遇2500℃火焰不熔不滴，瞬间转化为无定形碳质保护层
        "melting_point_c": None, # 三维交联无熔点
        "max_service_temp_c": 160.0, # 短暂抗数千度高温火炬冲刷
        "typical_applications": "高温密封烧蚀无石棉盘根、航天耐热碳前驱体、阻燃赛车服衬垫、化学品防护毯",
        "representative_brands": "Kynol (群荣化学), Novoloid",
        "tech_status_2026": "遇火碳化转化率极高且不收缩，常与碳纤维、芳纶混纺用于严苛火灾阻隔层与高端活性碳纤维前驱体",
        "is_bio_based": 0,
        "is_biodegradable": 0,
        "is_high_performance": 1,
        "aliases": [("酚醛纤维", "colloquial"), ("Kynol", "trade_name"), ("Novoloid", "trade_name"), ("NOV", "iso_code")],
        "standards": [("ISO", "ISO 2076:2021", "Novoloid"), ("GB", "GB/T 4146.1-2020", "酚醛纤维命名")]
    },
    {
        "category_code": "HP_THERMO",
        "code": "MEL",
        "name_zh": "三聚氰胺甲醛纤维 (美耐皿纤维/Basofil)",
        "name_en": "Melamine Fiber",
        "chemical_name": "三聚氰胺与甲醛交联缩聚高分子",
        "chemical_formula": "Cross-linked Melamine-Formaldehyde",
        "cas_number": "25036-13-9",
        "generation": "第3代高效隔热阻燃无机/有机杂化感纤维",
        "discovery_year": "1990s",
        "commercial_year": "1997",
        "pioneering_entity": "BASF (巴斯夫 Basofil / 现属 Basofil LLC)",
        "spinning_method": "水溶液离心旋转熔体/溶液挤出纺丝后热风固化交联",
        "density_g_cm3": 1.40,
        "tensile_strength_cn_dtex": 2.0,
        "tensile_strength_gpa": 0.28,
        "tensile_modulus_gpa": 7.0,
        "elongation_at_break_pct": 12.0,
        "moisture_regain_pct": 5.5,
        "loi_pct": 32.0,
        "melting_point_c": None, # 不熔融，发烟毒性极低
        "max_service_temp_c": 200.0,
        "typical_applications": "高铁与民航客机座椅防火阻隔衬垫、消防隔热手套耐热毡、工业炉窑阻火屏障",
        "representative_brands": "Basofil (巴斯夫), 密胺纤维",
        "tech_status_2026": "低游离甲醛绿色缩聚工艺达到欧标极高环保级别，在高端公共交通工具阻燃防火安全领域应用稳固",
        "is_bio_based": 0,
        "is_biodegradable": 0,
        "is_high_performance": 1,
        "aliases": [("密胺纤维", "colloquial"), ("三聚氰胺纤维", "standard_name"), ("Basofil", "trade_name"), ("MEL", "iso_code")],
        "standards": [("GB", "GB/T 4146.1-2020", "三聚氰胺纤维"), ("ISO", "ISO 2076:2021", "Melamine")]
    }
]

print(f"Loaded Part 2: {len(FIBERS_PART_2)} chemical fibers.")
