# -*- coding: utf-8 -*-
"""
化学纤维数据集 Part 4 (补全经典与高附加值特种化学纤维):
- 竹浆粘胶纤维 (Bamboo Pulp Fiber)
- 低熔点聚酯粘合纤维 (LMPET)
- 双组分皮芯复合纤维 (ES Fiber - PE/PP, PE/PET)
- 半芳香族耐高温聚酰胺纤维 (PPA / PA9T / PA10T)
- 全生物基长碳链聚酰胺1010纤维 (PA1010)
- 聚酰胺610纤维 (PA610)
- 聚碳酸亚丙酯二氧化碳基纤维 (PPC Fiber)
- 纳米纤维素宏观连续长丝 (Nanocellulose Macrofiber - CNF)
- 莫来石连续耐火陶瓷纤维 (Mullite Ceramic Fiber)
- 氧化锆超高温耐火纤维 (Zirconia Fiber - ZrO2)
"""

FIBERS_PART_4 = [
    {
        "category_code": "REG_CELL",
        "code": "BAMBOO",
        "name_zh": "竹浆纤维 (竹粘胶纤维/竹素纤维)",
        "name_en": "Bamboo Pulp Viscose Fiber",
        "chemical_name": "竹子纤维素经黄原酸酯法再生聚合物",
        "chemical_formula": "(C6H10O5)n",
        "cas_number": "68442-85-3",
        "generation": "第2代特色天然生物质人造纤维",
        "discovery_year": "1990s",
        "commercial_year": "2002",
        "pioneering_entity": "吉林化纤 (天竹纤维)",
        "spinning_method": "湿法纺丝 (竹材粉碎蒸煮制浆、黄化溶解后湿法成形)",
        "density_g_cm3": 1.50,
        "tensile_strength_cn_dtex": 2.3,
        "tensile_strength_gpa": 0.34,
        "tensile_modulus_gpa": 5.8,
        "elongation_at_break_pct": 21.0,
        "moisture_regain_pct": 13.5,
        "loi_pct": 19.5,
        "melting_point_c": None,
        "max_service_temp_c": 120.0,
        "typical_applications": "天然抑菌毛巾、亲肤凉爽夏季凉席面料、竹纤维袜子内衣、卫生擦拭无纺布",
        "representative_brands": "Tanboocel (天竹 / 吉林化纤)",
        "tech_status_2026": "绿色循环闭环清洁制浆技术全面升级，天然多孔横截面赋予其优异的透气排湿与抑菌防臭特性",
        "is_bio_based": 1,
        "is_biodegradable": 1,
        "is_high_performance": 0,
        "aliases": [("竹纤维", "colloquial"), ("天竹", "trade_name"), ("Tanboocel", "trade_name")],
        "standards": [("GB", "GB/T 22705-2008", "竹浆粕"), ("GB", "FZ/T 52010-2014", "竹浆粘胶短纤维")]
    },
    {
        "category_code": "SYN_PET",
        "code": "LMPET",
        "name_zh": "低熔点聚酯复合纤维 (LMPET热熔粘结纤维)",
        "name_en": "Low-Melting Polyester Fiber (LMPET)",
        "chemical_name": "PET芯层 / 间苯二甲酸/己二酸改性共聚酯外皮层",
        "chemical_formula": "PET Core / Co-PET Sheath",
        "cas_number": "25038-59-9",
        "generation": "第2代环保功能热熔粘合纤维",
        "discovery_year": "1980s",
        "commercial_year": "1990s",
        "pioneering_entity": "Huvis (韩国汇维仕) / 远东新世纪 / 恒逸石化",
        "spinning_method": "双组分皮芯复合熔融纺丝 (皮层熔点精确控制在110-160℃，芯层PET熔点255℃)",
        "density_g_cm3": 1.36,
        "tensile_strength_cn_dtex": 3.6,
        "tensile_strength_gpa": 0.49,
        "tensile_modulus_gpa": 9.0,
        "elongation_at_break_pct": 35.0,
        "moisture_regain_pct": 0.4,
        "loi_pct": 20.5,
        "melting_point_c": 110.0, # 皮层熔点110℃起熔融粘合
        "max_service_temp_c": 100.0,
        "typical_applications": "替代传统有毒胶水制作床垫热风棉、汽车内饰顶棚隔音棉、无胶热轧水刺无纺布、环保过滤棉",
        "representative_brands": "Huvis LMF, 远东新世纪LMPET",
        "tech_status_2026": "彻底取缔脲醛树脂化学粘合剂，成为万亿级家居软装与汽车NVH降噪隔热棉绿色升级第一大材料",
        "is_bio_based": 0,
        "is_biodegradable": 0,
        "is_high_performance": 0,
        "aliases": [("低熔点涤纶", "colloquial"), ("LMPET", "abbreviation"), ("皮芯热熔丝", "colloquial")],
        "standards": [("GB", "GB/T 33617-2017", "低熔点聚酯(LMPET)复合短纤维")]
    },
    {
        "category_code": "SYN_PO",
        "code": "ES-F",
        "name_zh": "双组分聚烯烃复合纤维 (ES纤维 / 热风粘合纤维)",
        "name_en": "Bicomponent Polyolefin Composite Fiber (ES Fiber)",
        "chemical_name": "PE外皮 / PP或PET内芯双组分复合聚合物",
        "chemical_formula": "PE Sheath (Tm 130℃) / PP Core (Tm 165℃)",
        "cas_number": None,
        "generation": "第2代高蓬松亲水复合纤维",
        "discovery_year": "1970s",
        "commercial_year": "1980s",
        "pioneering_entity": "Chisso (日本捷索 / JNC) / 广州纤维",
        "spinning_method": "复合熔融纺丝 (双组分同轴挤出复合，受热时PE皮层软化粘接而PP芯层保持挺括)",
        "density_g_cm3": 0.93,
        "tensile_strength_cn_dtex": 3.0,
        "tensile_strength_gpa": 0.28,
        "tensile_modulus_gpa": 3.0,
        "elongation_at_break_pct": 50.0,
        "moisture_regain_pct": 0.1,
        "loi_pct": 18.0,
        "melting_point_c": 130.0,
        "max_service_temp_c": 90.0,
        "typical_applications": "婴儿高端极软纸尿裤面层热风无纺布、女性卫生巾亲肤表层、高透气KN95口罩支撑层",
        "representative_brands": "ES Fiber (JNC), 恒天江南高纤ES",
        "tech_status_2026": "超细旦(0.8-1.2 dtex)高蓬松弱酸性表层改性ES纤维全面普及，触感如蚕丝般丝滑亲肤",
        "is_bio_based": 0,
        "is_biodegradable": 0,
        "is_high_performance": 0,
        "aliases": [("ES纤维", "trade_name"), ("热风纤维", "colloquial"), ("皮芯复合纤维", "colloquial")],
        "standards": [("GB", "FZ/T 52028-2014", "聚乙烯/聚丙烯复合短纤维(PE/PP)")]
    },
    {
        "category_code": "SYN_PA",
        "code": "PPA-F",
        "name_zh": "半芳香族高温聚酰胺纤维 (PPA / PA9T / PA10T纤维)",
        "name_en": "Polyphthalamide High-Temperature Fiber (PPA / PA9T)",
        "chemical_name": "对苯二甲酸与1,9-壬二胺/1,10-癸二胺半芳香族聚酰胺",
        "chemical_formula": "[-NH-(CH2)9-NH-CO-C6H4-CO-]n",
        "cas_number": "165848-52-8",
        "generation": "第3代耐回流焊高温特种尼龙",
        "discovery_year": "1980s",
        "commercial_year": "1998",
        "pioneering_entity": "Kuraray (日本可乐丽 Genestar) / 金发科技",
        "spinning_method": "高温熔融纺丝与高倍热牵伸 (熔体温度达320℃)",
        "density_g_cm3": 1.17,
        "tensile_strength_cn_dtex": 7.5,
        "tensile_strength_gpa": 0.88,
        "tensile_modulus_gpa": 6.8,
        "elongation_at_break_pct": 18.0,
        "moisture_regain_pct": 0.9, # 吸水率极低，尺寸稳定性远胜PA66
        "loi_pct": 26.0,
        "melting_point_c": 306.0,
        "max_service_temp_c": 170.0,
        "typical_applications": "SMT无铅回流焊耐热电子元器件包装织物、高耐温汽车燃油蒸汽管路增强套管、高温酸碱工业过滤布",
        "representative_brands": "Genestar (可乐丽 PA9T), Vicnyl (金发科技 PA10T)",
        "tech_status_2026": "生物基癸二胺合成PA10T纤维全面产业化，耐水解与耐热蠕变性能在汽车动力总成管路实现关键替代",
        "is_bio_based": 1,
        "is_biodegradable": 0,
        "is_high_performance": 1,
        "aliases": [("PPA纤维", "abbreviation"), ("高温尼龙纤维", "colloquial"), ("PA9T", "abbreviation"), ("PA10T", "abbreviation")],
        "standards": [("ASTM", "ASTM D5336", "Standard Specification for Polyphthalamide (PPA) Materials")]
    },
    {
        "category_code": "SYN_PA",
        "code": "PA1010",
        "name_zh": "聚酰胺1010纤维 (锦纶1010/全生物基长碳链尼龙)",
        "name_en": "Polyamide 1010 Fiber (Nylon 1010)",
        "chemical_name": "聚癸二酰癸二胺 (100%全蓖麻油来源)",
        "chemical_formula": "[-NH-(CH2)10-NH-CO-(CH2)8-CO-]n",
        "cas_number": "28774-87-0",
        "generation": "第2代中国独创全生物基长碳链尼龙",
        "discovery_year": "1958",
        "commercial_year": "1960s",
        "pioneering_entity": "中科院化学所 / 上海赛科 / 山东东宝",
        "spinning_method": "熔体纺丝 (蓖麻油深加工制备癸二胺与癸二酸缩聚物)",
        "density_g_cm3": 1.05,
        "tensile_strength_cn_dtex": 4.5,
        "tensile_strength_gpa": 0.47,
        "tensile_modulus_gpa": 2.8,
        "elongation_at_break_pct": 36.0,
        "moisture_regain_pct": 1.5, # 极低吸湿率
        "loi_pct": 21.5,
        "melting_point_c": 205.0,
        "max_service_temp_c": 115.0,
        "typical_applications": "海洋抗附着耐盐雾特种绳缆、高级工业毛刷丝、精密光纤被覆层、汽车刹车气动管路强化网",
        "representative_brands": "Rilsan D, 东宝锦纶1010",
        "tech_status_2026": "具有100%生物基碳含量认证，耐高低温冲击与耐油耐溶剂性优异，出口欧洲高端机械管路与轻量化绳缆",
        "is_bio_based": 1,
        "is_biodegradable": 0,
        "is_high_performance": 0,
        "aliases": [("锦纶1010", "colloquial"), ("尼龙1010", "colloquial"), ("PA1010", "iso_code")],
        "standards": [("GB", "GB/T 4146.1-2020", "聚酰胺纤维")]
    },
    {
        "category_code": "BIO_FDCA",
        "code": "PPC-F",
        "name_zh": "聚碳酸亚丙酯纤维 (PPC/二氧化碳共聚纤维)",
        "name_en": "Polypropylene Carbonate Fiber (CO2-derived PPC)",
        "chemical_name": "二氧化碳与环氧丙烷无规交替共聚物",
        "chemical_formula": "[-O-CH(CH3)-CH2-O-CO-]n",
        "cas_number": "25511-85-7",
        "generation": "第4代碳中和负碳固碳新型纤维",
        "discovery_year": "1969",
        "commercial_year": "2021",
        "pioneering_entity": "Shohei Inoue (井上祥平) / 中科院长春应化所 (王献红团队)",
        "spinning_method": "熔融纺丝或湿纺 (高活性双金属催化二氧化碳固定缩聚)",
        "density_g_cm3": 1.30,
        "tensile_strength_cn_dtex": 2.8,
        "tensile_strength_gpa": 0.36,
        "tensile_modulus_gpa": 2.2,
        "elongation_at_break_pct": 60.0,
        "moisture_regain_pct": 0.8,
        "loi_pct": 22.0,
        "melting_point_c": 115.0, # 热分解温度可达250℃(经封端改性)
        "max_service_temp_c": 80.0,
        "typical_applications": "负碳环保可堆肥包装布、农用可控降解防尘网、医用一次性敷料无纺布",
        "representative_brands": "PPC Fiber, 中科院负碳纤维",
        "tech_status_2026": "纤维中固定工业捕集废气CO2质量占比超40%，高热稳定性嵌段改性技术打通工业级高速熔纺瓶颈",
        "is_bio_based": 0,
        "is_biodegradable": 1,
        "is_high_performance": 0,
        "aliases": [("PPC纤维", "abbreviation"), ("二氧化碳纤维", "colloquial"), ("固碳纤维", "colloquial")],
        "standards": [("GB", "GB/T 32367-2015", "聚碳酸亚丙酯(PPC)树脂")]
    },
    {
        "category_code": "REG_CELL",
        "code": "CNF-MACRO",
        "name_zh": "微纳原纤化纳米纤维素宏观连续纤维 (CNF长丝)",
        "name_en": "Cellulose Nanofiber Macrofilament (CNF Fiber)",
        "chemical_name": "纯植物源一维纤维素纳米原纤高度定向聚集体",
        "chemical_formula": "(C6H10O5)n Nanocrystal",
        "cas_number": "9004-34-6",
        "generation": "第4代全天然超高强纳米组装长丝",
        "discovery_year": "2010s",
        "commercial_year": "2023",
        "pioneering_entity": "KTH 皇家理工学院 (Söderberg团队) / 华南理工 / 中科大",
        "spinning_method": "流体动力学微流控对准剪切自组装湿法纺丝 (无需任何衍生化化学试剂，纯物理纳米微纤对齐)",
        "density_g_cm3": 1.52,
        "tensile_strength_cn_dtex": 12.0,
        "tensile_strength_gpa": 1.60, # 强度逼近玻璃纤维，断裂韧性极佳
        "tensile_modulus_gpa": 45.0,
        "elongation_at_break_pct": 7.5,
        "moisture_regain_pct": 8.5,
        "loi_pct": 21.0,
        "melting_point_c": None,
        "max_service_temp_c": 160.0,
        "typical_applications": "生物基全降解高刚度绿色汽车轻量化车身复合材料、环保可降解绿色防弹纤维、人造肌腱修复软组织",
        "representative_brands": "NanocellFil, 华南理工纳米纤维素长丝",
        "tech_status_2026": "宏观连续拉丝速度达到50 m/min，比强度超越普通轻质合金，成为最具潜力的全生物源结构增强长丝",
        "is_bio_based": 1,
        "is_biodegradable": 1,
        "is_high_performance": 1,
        "aliases": [("CNF纤维", "abbreviation"), ("纳米纤维素丝", "colloquial")],
        "standards": [("ISO", "ISO/TS 20477", "Nanotechnologies - Standard terms and definitions for cellulose nanomaterial")]
    },
    {
        "category_code": "INORG_CERAMIC",
        "code": "MULLITE-F",
        "name_zh": "连续莫来石陶瓷纤维 (Mullite Fiber)",
        "name_en": "Continuous Mullite Ceramic Fiber",
        "chemical_name": "化学计量比多晶莫来石 (3Al2O3·2SiO2)",
        "chemical_formula": "3Al2O3·2SiO2 (72% Al2O3, 28% SiO2)",
        "cas_number": "1302-93-8",
        "generation": "第3代超高温抗蠕变陶瓷纤维",
        "discovery_year": "1970s",
        "commercial_year": "1980s",
        "pioneering_entity": "3M (Nextel 440) / 蔚蓝材料",
        "spinning_method": "溶胶-凝胶干法纺丝与1350℃精密相变热处理",
        "density_g_cm3": 3.05,
        "tensile_strength_cn_dtex": 7.0,
        "tensile_strength_gpa": 2.10,
        "tensile_modulus_gpa": 220.0,
        "elongation_at_break_pct": 1.0,
        "moisture_regain_pct": 0.0,
        "loi_pct": 100.0,
        "melting_point_c": 1850.0,
        "max_service_temp_c": 1300.0, # 高温抗蠕变能力优于纯氧化铝
        "typical_applications": "航天飞机隔热瓦缝隙耐冲刷密封编织绳、高温工业燃烧炉微波加热衬套、航天防热微流星防护屏",
        "representative_brands": "Nextel 440 (3M), 莫来石连续丝",
        "tech_status_2026": "极低热导率与极高热震稳定性，在1200℃以上连续服役抗蠕变性能保持世界领先",
        "is_bio_based": 0,
        "is_biodegradable": 0,
        "is_high_performance": 1,
        "aliases": [("莫来石纤维", "colloquial"), ("硅酸铝陶瓷纤维", "standard_name")],
        "standards": [("GB", "GB/T 3003-2017", "耐火材料 陶瓷纤维及制品")]
    },
    {
        "category_code": "INORG_CERAMIC",
        "code": "ZRO2-F",
        "name_zh": "连续氧化锆耐火陶瓷纤维 (ZrO2纤维)",
        "name_en": "Continuous Zirconia Ceramic Fiber",
        "chemical_name": "钇稳定四方晶相多晶氧化锆 (YSZ)",
        "chemical_formula": "ZrO2-Y2O3 (8 mol% Y2O3)",
        "cas_number": "1314-23-4",
        "generation": "第3代耐极限超高温无机纤维",
        "discovery_year": "1960s",
        "commercial_year": "1974",
        "pioneering_entity": "Union Carbide (Zircar) / 中科院上海硅酸盐所",
        "spinning_method": "先驱体浸渍热解法(粘胶布载体浸渍锆盐烧结)或溶胶凝胶拉丝法",
        "density_g_cm3": 5.68,
        "tensile_strength_cn_dtex": 4.5,
        "tensile_strength_gpa": 1.80,
        "tensile_modulus_gpa": 180.0,
        "elongation_at_break_pct": 1.0,
        "moisture_regain_pct": 0.0,
        "loi_pct": 100.0,
        "melting_point_c": 2700.0, # 常见商业化学纤维中熔点最高之一
        "max_service_temp_c": 2200.0, # 极限耐受2200℃以上高温
        "typical_applications": "超高温晶体生长炉(蓝宝石/单晶硅长晶炉)2000℃隔热绝热屏、核聚变托卡马克内壁绝热衬里、火箭发动机喷管极端防热层",
        "representative_brands": "Zircar Zirconia, 上硅所氧化锆纤维毡",
        "tech_status_2026": "纳米氧化钇微相稳定技术防止晶型高温相变粉化，长期耐受2000℃超高温氧化环境且蒸气压极低",
        "is_bio_based": 0,
        "is_biodegradable": 0,
        "is_high_performance": 1,
        "aliases": [("氧化锆纤维", "colloquial"), ("ZrO2纤维", "abbreviation"), ("Zircar", "trade_name")],
        "standards": [("GB", "GB/T 3003-2017", "耐火材料 陶瓷纤维及制品")]
    }
]

print(f"Loaded Part 4: {len(FIBERS_PART_4)} chemical fibers.")
