# -*- coding: utf-8 -*-
"""
化学纤维数据集 Part 1:
1. 再生纤维与人造纤维 (Cellulose, Protein, Polysaccharide)
2. 常规与差别化合成纤维 (PET, PA, PAN, PO, PU, PVA, Halogenated)
"""

FIBERS_PART_1 = [
    # ==================== 1. 再生纤维素纤维 (REG_CELL) ====================
    {
        "category_code": "REG_CELL",
        "code": "CV",
        "name_zh": "粘胶纤维 (普通粘胶/人造棉/人造丝)",
        "name_en": "Viscose Rayon",
        "chemical_name": "再生纤维素 (黄原酸酯法)",
        "chemical_formula": "(C6H10O5)n",
        "cas_number": "68442-85-3",
        "generation": "第1代人造纤维",
        "discovery_year": "1891",
        "commercial_year": "1905",
        "pioneering_entity": "Cross, Bevan & Beadle (英国 Courtaulds)",
        "spinning_method": "湿法纺丝 (硫酸/硫酸锌/硫酸钠酸浴凝固)",
        "density_g_cm3": 1.51,
        "tensile_strength_cn_dtex": 2.2,
        "tensile_strength_gpa": 0.33,
        "tensile_modulus_gpa": 5.5,
        "elongation_at_break_pct": 20.0,
        "moisture_regain_pct": 13.0,
        "loi_pct": 19.5,
        "melting_point_c": None, # 不熔，260-300℃炭化
        "max_service_temp_c": 120.0,
        "typical_applications": "服装内衣、面料衬里、家用纺织品、医用纱布水刺无纺布、湿巾",
        "representative_brands": "Danufil, Rayon, 人造丝, 人造棉",
        "tech_status_2026": "产业规模成熟；全面升级为密闭化二硫化碳全回收环保生产线与循环再生棉浆粕源",
        "is_bio_based": 1,
        "is_biodegradable": 1,
        "is_high_performance": 0,
        "aliases": [("Rayon", "trade_name"), ("人造棉", "colloquial"), ("人造丝", "colloquial"), ("粘纤", "abbreviation"), ("CV", "iso_code")],
        "standards": [("ISO", "ISO 2076:2021", "Man-made fibres - Generic names"), ("GB", "GB/T 4146.1-2020", "纺织品 化学纤维 第1部分：属名")]
    },
    {
        "category_code": "REG_CELL",
        "code": "CMD",
        "name_zh": "莫代尔纤维 (高湿模量粘胶纤维)",
        "name_en": "Modal Fiber",
        "chemical_name": "高湿模量改性再生纤维素",
        "chemical_formula": "(C6H10O5)n",
        "cas_number": "68442-85-3",
        "generation": "第2代差别化纤维",
        "discovery_year": "1951",
        "commercial_year": "1960s",
        "pioneering_entity": "Tachikawa (日本立川) / 兰精 (Lenzing)",
        "spinning_method": "改性湿法纺丝 (慢凝固浴、高拉伸低酸工艺)",
        "density_g_cm3": 1.52,
        "tensile_strength_cn_dtex": 3.4,
        "tensile_strength_gpa": 0.52,
        "tensile_modulus_gpa": 7.0,
        "elongation_at_break_pct": 14.0,
        "moisture_regain_pct": 12.5,
        "loi_pct": 19.5,
        "melting_point_c": None,
        "max_service_temp_c": 130.0,
        "typical_applications": "高档贴身内衣、床品家纺、高支针织面料、柔顺亲肤混纺纺织品",
        "representative_brands": "Lenzing Modal, MicroModal",
        "tech_status_2026": "全球高档纺织核心原料，广泛结合环保认证榉木浆与零碳碳中和认证",
        "is_bio_based": 1,
        "is_biodegradable": 1,
        "is_high_performance": 0,
        "aliases": [("Modal", "trade_name"), ("木代尔", "colloquial"), ("高湿模量粘胶", "standard_name"), ("CMD", "iso_code")],
        "standards": [("GB", "GB/T 22704-2019", "莫代尔纤维及混纺织物"), ("ISO", "ISO 2076:2021", "Modal definition")]
    },
    {
        "category_code": "REG_CELL",
        "code": "CLY",
        "name_zh": "莱赛尔纤维 (天丝/溶剂法纤维素纤维)",
        "name_en": "Lyocell Fiber",
        "chemical_name": "N-甲基氧化吗啉 (NMMO) 溶剂法再生纤维素",
        "chemical_formula": "(C6H10O5)n",
        "cas_number": "68442-85-3",
        "generation": "第3代绿色人造纤维",
        "discovery_year": "1972",
        "commercial_year": "1992",
        "pioneering_entity": "Akzo Nobel / Courtaulds / Lenzing",
        "spinning_method": "干湿法纺丝 (NMMO水溶液直接物理溶解，溶剂回收率>99.5%)",
        "density_g_cm3": 1.50,
        "tensile_strength_cn_dtex": 4.2,
        "tensile_strength_gpa": 0.63,
        "tensile_modulus_gpa": 11.0,
        "elongation_at_break_pct": 13.0,
        "moisture_regain_pct": 11.5,
        "loi_pct": 20.0,
        "melting_point_c": None,
        "max_service_temp_c": 140.0,
        "typical_applications": "中高端服装面料、牛仔服饰、水刺高级医美无纺布、电池隔膜纸基材料",
        "representative_brands": "Tencel (天丝), Lenzing Lyocell, 中纺院绿纤",
        "tech_status_2026": "绿色纤维主导品种，百万吨级产能落地，原纤化调控与非原纤化改性技术全面成熟",
        "is_bio_based": 1,
        "is_biodegradable": 1,
        "is_high_performance": 0,
        "aliases": [("Tencel", "trade_name"), ("天丝", "colloquial"), ("溶剂法纤维素纤维", "standard_name"), ("CLY", "iso_code")],
        "standards": [("GB", "GB/T 22703-2008", "莱赛尔本色短纤维"), ("ISO", "ISO 2076:2021", "Lyocell generic name")]
    },
    {
        "category_code": "REG_CELL",
        "code": "CUP",
        "name_zh": "铜氨纤维",
        "name_en": "Cupro (Cuprammonium Rayon)",
        "chemical_name": "氢氧化四氨合铜络合物溶剂法再生纤维素",
        "chemical_formula": "(C6H10O5)n",
        "cas_number": "68442-85-3",
        "generation": "第1代人造纤维",
        "discovery_year": "1897",
        "commercial_year": "1919",
        "pioneering_entity": "Bemberg (宾霸 / 旭化成 Asahi Kasei)",
        "spinning_method": "漏斗式湿法喷丝成形 (铜氨络合物水溶液溶解棉短绒)",
        "density_g_cm3": 1.52,
        "tensile_strength_cn_dtex": 2.3,
        "tensile_strength_gpa": 0.35,
        "tensile_modulus_gpa": 6.5,
        "elongation_at_break_pct": 18.0,
        "moisture_regain_pct": 12.0,
        "loi_pct": 20.0,
        "melting_point_c": None,
        "max_service_temp_c": 125.0,
        "typical_applications": "奢华西服里料、高级真丝触感时装、透气面膜基布、超纯无尘擦拭布",
        "representative_brands": "Bemberg (宾霸), Asahi Kasei Cupro",
        "tech_status_2026": "以棉籽短绒为全降解原料的高端闭环制造，日本与中国新增高洁净化生产基地",
        "is_bio_based": 1,
        "is_biodegradable": 1,
        "is_high_performance": 0,
        "aliases": [("Bemberg", "trade_name"), ("宾霸", "trade_name"), ("铜氨丝", "colloquial"), ("CUP", "iso_code")],
        "standards": [("GB", "FZ/T 52022-2012", "铜氨短纤维"), ("ISO", "ISO 2076:2021", "Cupro definition")]
    },
    {
        "category_code": "REG_CELL",
        "code": "CA",
        "name_zh": "醋酯纤维 (二醋酸纤维)",
        "name_en": "Acetate Fiber (Cellulose Diacetate)",
        "chemical_name": "二乙酰基纤维素酯",
        "chemical_formula": "[C6H7O2(OH)x(OOCCH3)y]n (y≈2.4)",
        "cas_number": "9004-35-7",
        "generation": "第1代半合成纤维",
        "discovery_year": "1865",
        "commercial_year": "1924",
        "pioneering_entity": "Dreyfus 兄弟 (Celanese / 塞拉尼斯)",
        "spinning_method": "干法纺丝 (丙酮溶剂溶解二醋酸纤维素，热空气挥发成形)",
        "density_g_cm3": 1.32,
        "tensile_strength_cn_dtex": 1.4,
        "tensile_strength_gpa": 0.18,
        "tensile_modulus_gpa": 3.8,
        "elongation_at_break_pct": 28.0,
        "moisture_regain_pct": 6.5,
        "loi_pct": 18.5,
        "melting_point_c": 260.0,
        "max_service_temp_c": 110.0,
        "typical_applications": "香烟滤嘴丝束、高端仿真丝礼服、轻奢围巾领带、女士缎面面料",
        "representative_brands": "Celanese Acetate, Eastman Estron",
        "tech_status_2026": "滤嘴丝束全面推广可自然堆肥降解新型增塑剂配方，纺织领域向超细高回弹长丝扩展",
        "is_bio_based": 1,
        "is_biodegradable": 1,
        "is_high_performance": 0,
        "aliases": [("醋酸纤维", "colloquial"), ("二醋酸", "abbreviation"), ("Celanese", "trade_name"), ("CA", "iso_code")],
        "standards": [("GB", "GB/T 4146.1-2020", "醋酯纤维定义"), ("ISO", "ISO 2076:2021", "Acetate")]
    },
    {
        "category_code": "REG_CELL",
        "code": "CTA",
        "name_zh": "三醋酯纤维 (三醋酸纤维)",
        "name_en": "Triacetate Fiber (Cellulose Triacetate)",
        "chemical_name": "三乙酰基纤维素酯",
        "chemical_formula": "[C6H7O2(OOCCH3)3]n",
        "cas_number": "9012-09-3",
        "generation": "第2代改性半合成纤维",
        "discovery_year": "1894",
        "commercial_year": "1954",
        "pioneering_entity": "Celanese / Courtaulds",
        "spinning_method": "干法纺丝 (二氯甲烷/甲醇混合溶剂挥发)",
        "density_g_cm3": 1.30,
        "tensile_strength_cn_dtex": 1.2,
        "tensile_strength_gpa": 0.16,
        "tensile_modulus_gpa": 4.0,
        "elongation_at_break_pct": 25.0,
        "moisture_regain_pct": 3.5,
        "loi_pct": 19.0,
        "melting_point_c": 300.0,
        "max_service_temp_c": 130.0,
        "typical_applications": "免烫高档西服、百褶裙、醋酸缎光礼服、光学偏光片保护膜前驱体",
        "representative_brands": "Soalon (日本三菱化学), Arnel",
        "tech_status_2026": "日本三菱化学独家技术持续垄断超高端时尚女装，环保非卤溶剂纺丝新产线落成",
        "is_bio_based": 1,
        "is_biodegradable": 1,
        "is_high_performance": 0,
        "aliases": [("三醋酸", "abbreviation"), ("三醋酯", "colloquial"), ("Soalon", "trade_name"), ("CTA", "iso_code")],
        "standards": [("ISO", "ISO 2076:2021", "Triacetate"), ("GB", "GB/T 4146.1-2020", "三醋酯纤维")]
    },
    {
        "category_code": "REG_CELL",
        "code": "BC",
        "name_zh": "细菌纤维素纤维",
        "name_en": "Bacterial Cellulose Fiber",
        "chemical_name": "醋酸杆菌生物合成超微纯纤维素",
        "chemical_formula": "(C6H10O5)n",
        "cas_number": "68442-85-3",
        "generation": "第4代生物工程合成纤维",
        "discovery_year": "1886",
        "commercial_year": "2010s",
        "pioneering_entity": "Brown / 现代合成生物学研究机构",
        "spinning_method": "生物反应发酵自组装网络，或微流控湿法定向纺丝",
        "density_g_cm3": 1.55,
        "tensile_strength_cn_dtex": 6.5,
        "tensile_strength_gpa": 1.0,
        "tensile_modulus_gpa": 25.0,
        "elongation_at_break_pct": 4.0,
        "moisture_regain_pct": 14.0,
        "loi_pct": 20.0,
        "melting_point_c": None,
        "max_service_temp_c": 150.0,
        "typical_applications": "人工血管移植管腔、高阶医用创面敷料、高端声学耳机振膜、柔性显示透明基底",
        "representative_brands": "Biofibe, Nata de coco derived medical pulp",
        "tech_status_2026": "生物反应器规模化量产达到千吨级，微流控连续拉伸制备高模长丝实现临床级体内植入认证",
        "is_bio_based": 1,
        "is_biodegradable": 1,
        "is_high_performance": 1,
        "aliases": [("BC纤维", "abbreviation"), ("生化纤维素", "colloquial")],
        "standards": [("ASTM", "ASTM F3160-16", "Standard Guide for Characterization of Bacterial Cellulose")]
    },

    # ==================== 2. 再生蛋白质纤维 (REG_PROT) ====================
    {
        "category_code": "REG_PROT",
        "code": "SPF",
        "name_zh": "大豆蛋白复合纤维",
        "name_en": "Soybean Protein Composite Fiber",
        "chemical_name": "大豆球蛋白/聚乙烯醇(PVA)或纤维素共混共聚物",
        "chemical_formula": "Protein-PVA graft polymer",
        "cas_number": None,
        "generation": "第3代生物质人造纤维",
        "discovery_year": "1937",
        "commercial_year": "2000",
        "pioneering_entity": "李官奇 (中国原创发明) / 江山大豆纤维",
        "spinning_method": "湿法纺丝 (大豆粕提取豆粕球蛋白，与高聚物共混纺丝，乙二醛或无醛交联)",
        "density_g_cm3": 1.29,
        "tensile_strength_cn_dtex": 3.0,
        "tensile_strength_gpa": 0.39,
        "tensile_modulus_gpa": 4.5,
        "elongation_at_break_pct": 18.0,
        "moisture_regain_pct": 8.6,
        "loi_pct": 22.0,
        "melting_point_c": None,
        "max_service_temp_c": 120.0,
        "typical_applications": "保暖内衣、羊绒混纺大衣、亲肤养肤床品、抗菌母婴服饰",
        "representative_brands": "Soybean Silk, 大豆羊绒",
        "tech_status_2026": "第二代无醛生物酶交联与大豆蛋白高保留率技术全面推广，耐热水洗性大幅增强",
        "is_bio_based": 1,
        "is_biodegradable": 1,
        "is_high_performance": 0,
        "aliases": [("大豆纤维", "colloquial"), ("大豆蛋白丝", "trade_name"), ("SPF", "abbreviation")],
        "standards": [("GB", "FZ/T 52014-2010", "大豆蛋白复合短纤维")]
    },
    {
        "category_code": "REG_PROT",
        "code": "MCF",
        "name_zh": "牛奶酪蛋白纤维",
        "name_en": "Milk Casein Fiber",
        "chemical_name": "牛奶酪蛋白接枝共聚高分子",
        "chemical_formula": "Casein copolymer",
        "cas_number": "9000-71-9",
        "generation": "第2代人造纤维",
        "discovery_year": "1935",
        "commercial_year": "1936 / 2000s改性",
        "pioneering_entity": "Ferretti (Lanital / 意大利) / 现代高分子共混改良",
        "spinning_method": "湿法纺丝 (废弃牛奶提取酪蛋白后碱溶，酸浴凝固及交联)",
        "density_g_cm3": 1.30,
        "tensile_strength_cn_dtex": 2.5,
        "tensile_strength_gpa": 0.32,
        "tensile_modulus_gpa": 4.0,
        "elongation_at_break_pct": 22.0,
        "moisture_regain_pct": 7.0,
        "loi_pct": 23.0,
        "melting_point_c": None,
        "max_service_temp_c": 115.0,
        "typical_applications": "高端轻奢内衣、婴儿贴身织物、抑菌床品家纺、高档混纺羊毛衫",
        "representative_brands": "Lanital, QMilch, 普力纤维",
        "tech_status_2026": "全生物源无重金属交联工艺普及，利用变质牛奶资源化生产实现零石化添加",
        "is_bio_based": 1,
        "is_biodegradable": 1,
        "is_high_performance": 0,
        "aliases": [("牛奶丝", "colloquial"), ("酪蛋白纤维", "chemical_name"), ("Lanital", "trade_name")],
        "standards": [("GB", "FZ/T 52019-2012", "牛奶蛋白复合短纤维")]
    },
    {
        "category_code": "REG_PROT",
        "code": "RSF",
        "name_zh": "再生蚕丝蛋白纤维",
        "name_en": "Regenerated Silk Fibroin Fiber",
        "chemical_name": "天然蚕丝丝素蛋白再生聚合物",
        "chemical_formula": "Fibroin polypeptide",
        "cas_number": "9007-76-5",
        "generation": "第4代生物医用高分子纤维",
        "discovery_year": "1990s",
        "commercial_year": "2015",
        "pioneering_entity": "国内外高校科研机构及生物医用材料企业",
        "spinning_method": "微流控湿纺 / 静电纺丝 (天然下脚丝脱胶溶解于六氟异丙醇或氯化钙-乙醇水溶液)",
        "density_g_cm3": 1.35,
        "tensile_strength_cn_dtex": 3.8,
        "tensile_strength_gpa": 0.51,
        "tensile_modulus_gpa": 12.0,
        "elongation_at_break_pct": 16.0,
        "moisture_regain_pct": 11.0,
        "loi_pct": 24.0,
        "melting_point_c": None,
        "max_service_temp_c": 130.0,
        "typical_applications": "人工韧带与软骨支架、神经导管、无疤痕缝合线、可穿戴生物传感水凝胶基质",
        "representative_brands": "SilkProtec, FibroinSilk",
        "tech_status_2026": "多项三类医疗器械获批上市，具有优异的生物相容性与受控可吸收周期",
        "is_bio_based": 1,
        "is_biodegradable": 1,
        "is_high_performance": 1,
        "aliases": [("丝素纤维", "abbreviation"), ("再生真丝", "colloquial")],
        "standards": [("YY", "YY/T 1680-2019", "组织工程医疗器械产品 丝素蛋白")]
    },

    # ==================== 3. 其他天然高分子基多糖纤维 (REG_POLY) ====================
    {
        "category_code": "REG_POLY",
        "code": "ALG",
        "name_zh": "海藻酸盐纤维 (海藻纤维)",
        "name_en": "Alginate Fiber",
        "chemical_name": "海藻酸钙/海藻酸钠多糖高分子",
        "chemical_formula": "[(C6H7O6)2Ca]n",
        "cas_number": "9005-38-3",
        "generation": "第2代特种医用人造纤维",
        "discovery_year": "1883",
        "commercial_year": "1940s",
        "pioneering_entity": "Stanford / Courtaulds",
        "spinning_method": "水相湿法纺丝 (海藻酸钠水溶液挤入氯化钙水浴进行离子置换凝胶)",
        "density_g_cm3": 1.70,
        "tensile_strength_cn_dtex": 2.2,
        "tensile_strength_gpa": 0.37,
        "tensile_modulus_gpa": 6.0,
        "elongation_at_break_pct": 12.0,
        "moisture_regain_pct": 16.0,
        "loi_pct": 34.0, # 天然优异阻燃，遇火不燃碳化
        "melting_point_c": None,
        "max_service_temp_c": 120.0,
        "typical_applications": "高吸收医用凝胶伤口敷料、阻燃防护服里衬、重金属吸附过滤棉、医美级护肤膜布",
        "representative_brands": "Kaltostat, Sorbsan, 青岛明月海藻",
        "tech_status_2026": "锌-铜-银复合抑菌离子海藻纤维量产；高吸水凝胶化敷料占据全球烧伤止血核心市场",
        "is_bio_based": 1,
        "is_biodegradable": 1,
        "is_high_performance": 0,
        "aliases": [("海藻纤维", "colloquial"), ("海藻酸钙纤维", "chemical_name"), ("ALG", "iso_code")],
        "standards": [("GB", "FZ/T 52026-2013", "海藻酸短纤维"), ("ISO", "ISO 2076:2021", "Alginate")]
    },
    {
        "category_code": "REG_POLY",
        "code": "CHT",
        "name_zh": "甲壳素与壳聚糖纤维",
        "name_en": "Chitin & Chitosan Fiber",
        "chemical_name": "聚脱乙酰氨基葡萄糖",
        "chemical_formula": "(C6H11NO4)n",
        "cas_number": "9012-76-4",
        "generation": "第3代生物活性纤维",
        "discovery_year": "1859",
        "commercial_year": "1990s",
        "pioneering_entity": "日本富士纺 (Fujibo) / 中国海洋大学等",
        "spinning_method": "湿法纺丝 (稀乙酸水溶液溶解，氢氧化钠凝固浴中再生中和脱酸)",
        "density_g_cm3": 1.45,
        "tensile_strength_cn_dtex": 1.8,
        "tensile_strength_gpa": 0.26,
        "tensile_modulus_gpa": 5.0,
        "elongation_at_break_pct": 15.0,
        "moisture_regain_pct": 14.0,
        "loi_pct": 26.0,
        "melting_point_c": None,
        "max_service_temp_c": 110.0,
        "typical_applications": "广谱抑菌内衣面料、慢伤口止血纱布、可降解手术缝线、环保果蔬保鲜功能布",
        "representative_brands": "Chitopoly, 恒天海龙壳聚糖短纤",
        "tech_status_2026": "高脱乙酰度(>95%)高强长丝技术成熟，实现与莱赛尔、纯棉的均匀混纺与原液着色",
        "is_bio_based": 1,
        "is_biodegradable": 1,
        "is_high_performance": 0,
        "aliases": [("甲壳素纤维", "colloquial"), ("几丁质纤维", "colloquial"), ("壳聚糖丝", "colloquial"), ("CHT", "iso_code")],
        "standards": [("GB", "FZ/T 52020-2012", "壳聚糖短纤维")]
    },
    {
        "category_code": "REG_POLY",
        "code": "ED",
        "name_zh": "二烯类弹性纤维 (天然胶乳橡胶丝)",
        "name_en": "Elastodiene (Natural Rubber Thread)",
        "chemical_name": "顺-1,4-聚异戊二烯 (交联橡胶)",
        "chemical_formula": "(C5H8)n",
        "cas_number": "9006-04-6",
        "generation": "第1代天然聚合物弹性纤维",
        "discovery_year": "1930s",
        "commercial_year": "1930s",
        "pioneering_entity": "Dunlop / 固特异",
        "spinning_method": "挤出凝固硫化法 (天然乳胶与硫化助剂挤出酸浴凝结并高温交联)",
        "density_g_cm3": 0.98,
        "tensile_strength_cn_dtex": 0.35,
        "tensile_strength_gpa": 0.035,
        "tensile_modulus_gpa": 0.005,
        "elongation_at_break_pct": 650.0,
        "moisture_regain_pct": 0.8,
        "loi_pct": 17.0,
        "melting_point_c": None,
        "max_service_temp_c": 85.0,
        "typical_applications": "松紧带、弹性织带、高拉伸蹦极绳索芯、传统弹力袜套口",
        "representative_brands": "Lastex, Rubber Flex",
        "tech_status_2026": "部分被氨纶替代，但凭借超大回弹力和抗反复大应变在重型弹性织物中维持专属市场",
        "is_bio_based": 1,
        "is_biodegradable": 1,
        "is_high_performance": 0,
        "aliases": [("乳胶丝", "colloquial"), ("橡筋线", "colloquial"), ("橡胶纤维", "standard_name"), ("ED", "iso_code")],
        "standards": [("ISO", "ISO 2076:2021", "Elastodiene"), ("GB", "GB/T 4146.1-2020", "二烯类弹性纤维")]
    },

    # ==================== 4. 聚酯系通用与改性合成纤维 (SYN_PET) ====================
    {
        "category_code": "SYN_PET",
        "code": "PET",
        "name_zh": "聚对苯二甲酸乙二醇酯纤维 (涤纶/聚酯纤维)",
        "name_en": "Polyethylene Terephthalate Fiber (Polyester)",
        "chemical_name": "聚对苯二甲酸乙二醇酯",
        "chemical_formula": "[-CO-C6H4-CO-O-(CH2)2-O-]n",
        "cas_number": "25038-59-9",
        "generation": "第1代大宗合成纤维",
        "discovery_year": "1941",
        "commercial_year": "1953",
        "pioneering_entity": "Whinfield & Dickson (CPA / ICI / 杜邦)",
        "spinning_method": "直接熔融纺丝法 (连续聚合-喷丝板挤出-侧吹风冷却-高速牵伸卷绕)",
        "density_g_cm3": 1.38,
        "tensile_strength_cn_dtex": 5.2,
        "tensile_strength_gpa": 0.72,
        "tensile_modulus_gpa": 12.5,
        "elongation_at_break_pct": 25.0,
        "moisture_regain_pct": 0.4,
        "loi_pct": 21.0,
        "melting_point_c": 260.0,
        "max_service_temp_c": 150.0,
        "typical_applications": "民用全领域服装、家纺床品、汽车轮胎帘子布、安全带、工业过滤网、非织造布",
        "representative_brands": "Dacron (达克纶), Terylene (特丽纶), 恒力聚酯, 桐昆涤纶",
        "tech_status_2026": "全球产销量最大的化学纤维（年产超6500万吨）；化学法循环再生(rPET)与原液着色成为行业标配",
        "is_bio_based": 0,
        "is_biodegradable": 0,
        "is_high_performance": 0,
        "aliases": [("涤纶", "colloquial"), ("Polyester", "trade_name"), ("Dacron", "trade_name"), ("PET", "iso_code")],
        "standards": [("GB", "GB/T 4146.1-2020", "聚酯纤维命名"), ("ISO", "ISO 2076:2021", "Polyester")]
    },
    {
        "category_code": "SYN_PET",
        "code": "PTT",
        "name_zh": "聚对苯二甲酸丙二醇酯纤维 (PTT纤维)",
        "name_en": "Polytrimethylene Terephthalate Fiber",
        "chemical_name": "聚对苯二甲酸-1,3-丙二醇酯",
        "chemical_formula": "[-CO-C6H4-CO-O-(CH2)3-O-]n",
        "cas_number": "26590-75-0",
        "generation": "第2代记忆型聚酯纤维",
        "discovery_year": "1941",
        "commercial_year": "1998",
        "pioneering_entity": "壳牌 (Shell Corterra) / 杜邦 (DuPont Sorona)",
        "spinning_method": "熔体纺丝 (生物发酵法1,3-丙二醇与PTA缩聚物)",
        "density_g_cm3": 1.34,
        "tensile_strength_cn_dtex": 3.8,
        "tensile_strength_gpa": 0.51,
        "tensile_modulus_gpa": 3.5,
        "elongation_at_break_pct": 35.0,
        "moisture_regain_pct": 0.45,
        "loi_pct": 21.0,
        "melting_point_c": 228.0,
        "max_service_temp_c": 130.0,
        "typical_applications": "记忆弹力外套、高档抗皱西服、高端地毯、泳装瑜伽服、羽绒服防钻绒面料",
        "representative_brands": "Sorona (杜邦索罗娜), Corterra",
        "tech_status_2026": "生物基PDO单体自给率超90%，其Z字型分子链赋予其接近氨纶的优异弹性回复率",
        "is_bio_based": 1,
        "is_biodegradable": 0,
        "is_high_performance": 0,
        "aliases": [("PTT", "iso_code"), ("Sorona", "trade_name"), ("索罗娜", "trade_name"), ("聚丙酯", "colloquial")],
        "standards": [("GB", "GB/T 30102-2013", "聚对苯二甲酸丙二醇酯(PTT)牵伸丝")]
    },
    {
        "category_code": "SYN_PET",
        "code": "PBT",
        "name_zh": "聚对苯二甲酸丁二醇酯纤维 (PBT纤维)",
        "name_en": "Polybutylene Terephthalate Fiber",
        "chemical_name": "聚对苯二甲酸-1,4-丁二醇酯",
        "chemical_formula": "[-CO-C6H4-CO-O-(CH2)4-O-]n",
        "cas_number": "26062-94-2",
        "generation": "第2代高回弹聚酯纤维",
        "discovery_year": "1970s",
        "commercial_year": "1980s",
        "pioneering_entity": "Celanese / 帝人 (Teijin)",
        "spinning_method": "熔融纺丝 (常规纺或高速纺丝与拉伸变形POY-DTY)",
        "density_g_cm3": 1.31,
        "tensile_strength_cn_dtex": 3.6,
        "tensile_strength_gpa": 0.47,
        "tensile_modulus_gpa": 2.8,
        "elongation_at_break_pct": 38.0,
        "moisture_regain_pct": 0.4,
        "loi_pct": 21.5,
        "melting_point_c": 225.0,
        "max_service_temp_c": 130.0,
        "typical_applications": "专业抗氯泳衣、高弹牛仔布、滑雪服、假发丝、高档牙刷刷毛及化妆刷毛",
        "representative_brands": "Wonderon, T-400 (与PET双组分复合)",
        "tech_status_2026": "在耐氯漂弹性服饰与工业刷丝领域稳步增长，与PET复合制备机械双螺旋转曲自卷曲纤维",
        "is_bio_based": 0,
        "is_biodegradable": 0,
        "is_high_performance": 0,
        "aliases": [("PBT", "iso_code"), ("聚丁酯", "colloquial")],
        "standards": [("GB", "FZ/T 54037-2014", "聚对苯二甲酸丁二醇酯(PBT)低弹丝")]
    },
    {
        "category_code": "SYN_PET",
        "code": "PEN",
        "name_zh": "聚萘二甲酸乙二醇酯纤维 (PEN纤维)",
        "name_en": "Polyethylene Naphthalate Fiber",
        "chemical_name": "聚2,6-萘二甲酸乙二醇酯",
        "chemical_formula": "[-CO-C10H6-CO-O-(CH2)2-O-]n",
        "cas_number": "25853-85-4",
        "generation": "第3代高性能聚酯纤维",
        "discovery_year": "1948",
        "commercial_year": "1995",
        "pioneering_entity": "Amoco / 帝人 (Teijin Teonex)",
        "spinning_method": "高温熔融纺丝与高倍热拉伸 (熔体温度约300℃)",
        "density_g_cm3": 1.36,
        "tensile_strength_cn_dtex": 8.5,
        "tensile_strength_gpa": 1.15,
        "tensile_modulus_gpa": 24.0,
        "elongation_at_break_pct": 8.0,
        "moisture_regain_pct": 0.3,
        "loi_pct": 24.0,
        "melting_point_c": 269.0,
        "max_service_temp_c": 165.0,
        "typical_applications": "超高速赛车高性能轮胎帘子线、深海系泊缆绳、高性能船帆布、高耐热绝缘层",
        "representative_brands": "Teonex, Pentex",
        "tech_status_2026": "作为尺寸稳定性优于涤纶、模量逼近芳纶的耐蠕变高模聚酯，在新能源车轮胎与航海帆布广泛应用",
        "is_bio_based": 0,
        "is_biodegradable": 0,
        "is_high_performance": 1,
        "aliases": [("PEN", "iso_code"), ("聚萘二甲酸乙二酯", "chemical_name"), ("Pentex", "trade_name")],
        "standards": [("ASTM", "ASTM D885", "Testing Tire Cords from Man-Made Organic-Base Fibers")]
    },
    {
        "category_code": "SYN_PET",
        "code": "CDP",
        "name_zh": "阳离子染料可染聚酯纤维 (CDP/ECDP)",
        "name_en": "Cationic Dyeable Polyester Fiber",
        "chemical_name": "含有间苯二甲酸二甲酯-5-磺酸钠共聚酯",
        "chemical_formula": "PET-co-SIPM copolymer",
        "cas_number": None,
        "generation": "第2代改性差别化聚酯",
        "discovery_year": "1960s",
        "commercial_year": "1970s",
        "pioneering_entity": "DuPont",
        "spinning_method": "熔体纺丝 (SIPM第三单体及PEG第四单体共聚酯)",
        "density_g_cm3": 1.37,
        "tensile_strength_cn_dtex": 4.2,
        "tensile_strength_gpa": 0.58,
        "tensile_modulus_gpa": 10.0,
        "elongation_at_break_pct": 28.0,
        "moisture_regain_pct": 0.5,
        "loi_pct": 21.0,
        "melting_point_c": 245.0,
        "max_service_temp_c": 130.0,
        "typical_applications": "多色提花织物、双色运动时装、免高压常压沸染色面料 (ECDP)",
        "representative_brands": "Dacron T-64, ECDP",
        "tech_status_2026": "常压低温可染(ECDP)节能减排品种占比超70%，显著降低染整热能消耗",
        "is_bio_based": 0,
        "is_biodegradable": 0,
        "is_high_performance": 0,
        "aliases": [("阳离子涤纶", "colloquial"), ("CDP", "abbreviation"), ("ECDP", "abbreviation")],
        "standards": [("GB", "GB/T 33615-2017", "阳离子染料可染聚酯低弹丝")]
    },

    # ==================== 5. 聚酰胺系合成纤维 (SYN_PA) ====================
    {
        "category_code": "SYN_PA",
        "code": "PA6",
        "name_zh": "聚酰胺6纤维 (锦纶6/尼龙6)",
        "name_en": "Polyamide 6 Fiber (Nylon 6)",
        "chemical_name": "聚己内酰胺",
        "chemical_formula": "[-NH-(CH2)5-CO-]n",
        "cas_number": "25038-54-4",
        "generation": "第1代大宗合成纤维",
        "discovery_year": "1938",
        "commercial_year": "1943",
        "pioneering_entity": "Paul Schlack (德国 IG Farben / BASF)",
        "spinning_method": "熔融纺丝 (己内酰胺开环聚合切片熔融挤出)",
        "density_g_cm3": 1.14,
        "tensile_strength_cn_dtex": 4.8,
        "tensile_strength_gpa": 0.55,
        "tensile_modulus_gpa": 3.8,
        "elongation_at_break_pct": 35.0,
        "moisture_regain_pct": 4.5,
        "loi_pct": 21.5,
        "melting_point_c": 220.0,
        "max_service_temp_c": 110.0,
        "typical_applications": "民用丝袜、贴身内衣、冲锋衣户外防撕裂面料、渔网、工业安全带、短纤地毯",
        "representative_brands": "Perlon (贝纶), Enka Nylon, 中石化巴陵己内酰胺",
        "tech_status_2026": "超细旦原液着色锦纶与己内酰胺化学闭环回收再生系统(Econyl等)大规模应用",
        "is_bio_based": 0,
        "is_biodegradable": 0,
        "is_high_performance": 0,
        "aliases": [("锦纶6", "colloquial"), ("尼龙6", "colloquial"), ("Perlon", "trade_name"), ("PA6", "iso_code")],
        "standards": [("GB", "GB/T 4146.1-2020", "聚酰胺纤维"), ("ISO", "ISO 2076:2021", "Polyamide")]
    },
    {
        "category_code": "SYN_PA",
        "code": "PA66",
        "name_zh": "聚酰胺66纤维 (锦纶66/尼龙66)",
        "name_en": "Polyamide 66 Fiber (Nylon 66)",
        "chemical_name": "聚己二酰己二胺",
        "chemical_formula": "[-NH-(CH2)6-NH-CO-(CH2)4-CO-]n",
        "cas_number": "32131-17-2",
        "generation": "第1代大宗合成纤维 (人类历史上首个纯合成纤维)",
        "discovery_year": "1935",
        "commercial_year": "1939",
        "pioneering_entity": "Wallace Carothers (卡罗瑟斯 / 杜邦 DuPont)",
        "spinning_method": "熔体纺丝 (己二胺己二酸盐聚合熔融高速纺丝)",
        "density_g_cm3": 1.14,
        "tensile_strength_cn_dtex": 5.5,
        "tensile_strength_gpa": 0.63,
        "tensile_modulus_gpa": 4.5,
        "elongation_at_break_pct": 28.0,
        "moisture_regain_pct": 4.0,
        "loi_pct": 22.0,
        "melting_point_c": 260.0,
        "max_service_temp_c": 130.0,
        "typical_applications": "高端汽车安全气囊布、高性能军用被服Cordura面料、重载工业帘子布、瑜伽高弹服",
        "representative_brands": "Nylon 66, Cordura (考杜拉), 华峰锦纶66",
        "tech_status_2026": "己二腈国产化技术彻底攻关放量，安全气囊与高耐磨军工装备全面自给并降本增效",
        "is_bio_based": 0,
        "is_biodegradable": 0,
        "is_high_performance": 0,
        "aliases": [("锦纶66", "colloquial"), ("尼龙66", "colloquial"), ("Nylon", "trade_name"), ("Cordura", "trade_name"), ("PA66", "iso_code")],
        "standards": [("GB", "GB/T 16604-2017", "聚酰胺66工业用帘子布"), ("ISO", "ISO 2076:2021", "Polyamide")]
    },
    {
        "category_code": "SYN_PA",
        "code": "PA56",
        "name_zh": "聚酰胺56纤维 (生物基锦纶56)",
        "name_en": "Polyamide 56 Fiber (Bio-based Nylon 56)",
        "chemical_name": "聚己二酰戊二胺",
        "chemical_formula": "[-NH-(CH2)5-NH-CO-(CH2)4-CO-]n",
        "cas_number": "119864-77-6",
        "generation": "第4代生物基合成纤维",
        "discovery_year": "2000s",
        "commercial_year": "2018",
        "pioneering_entity": "凯赛生物 (Cathay Biotech) / 中国纺科院",
        "spinning_method": "熔融纺丝 (淀粉玉米生物发酵法戊二胺与己二酸缩聚)",
        "density_g_cm3": 1.15,
        "tensile_strength_cn_dtex": 5.0,
        "tensile_strength_gpa": 0.58,
        "tensile_modulus_gpa": 4.2,
        "elongation_at_break_pct": 32.0,
        "moisture_regain_pct": 5.5, # 吸湿性明显优于PA6与PA66
        "loi_pct": 23.0,
        "melting_point_c": 254.0,
        "max_service_temp_c": 125.0,
        "typical_applications": "亲肤透气运动服、军旅阻燃战备服、高吸湿羽绒面料、绿色地毯长丝",
        "representative_brands": "Terryl (泰纶), 凯赛生物PA56",
        "tech_status_2026": "全球生物制造万吨级标杆，吸湿排汗指标逼近棉花，减碳幅度达50%以上",
        "is_bio_based": 1,
        "is_biodegradable": 0,
        "is_high_performance": 0,
        "aliases": [("生物基锦纶56", "colloquial"), ("泰纶", "trade_name"), ("Terryl", "trade_name"), ("PA56", "abbreviation")],
        "standards": [("GB", "FZ/T 54109-2018", "生物基聚酰胺56牵伸丝")]
    },
    {
        "category_code": "SYN_PA",
        "code": "PA11",
        "name_zh": "聚酰胺11纤维 (锦纶11/蓖麻油基尼龙)",
        "name_en": "Polyamide 11 Fiber (Nylon 11)",
        "chemical_name": "聚十一内酰胺",
        "chemical_formula": "[-NH-(CH2)10-CO-]n",
        "cas_number": "25035-04-5",
        "generation": "第2代长碳链生物基合成纤维",
        "discovery_year": "1942",
        "commercial_year": "1955",
        "pioneering_entity": "Arkema (阿科玛 Rilsan)",
        "spinning_method": "熔体纺丝 (100%源自蓖麻油经裂解制备11-氨基十一酸单体)",
        "density_g_cm3": 1.04,
        "tensile_strength_cn_dtex": 4.0,
        "tensile_strength_gpa": 0.42,
        "tensile_modulus_gpa": 2.5,
        "elongation_at_break_pct": 40.0,
        "moisture_regain_pct": 1.2,
        "loi_pct": 21.0,
        "melting_point_c": 187.0,
        "max_service_temp_c": 105.0,
        "typical_applications": "耐高低温工业管路织物、极地运动服饰、高韧性耐盐雾海洋特种绳网、高级刷丝",
        "representative_brands": "Rilsan (阿科玛), Rilsan Clear",
        "tech_status_2026": "作为全生物基长碳链高性能特种尼龙，在耐低温冲击与低吸水率领域保持高价值应用",
        "is_bio_based": 1,
        "is_biodegradable": 0,
        "is_high_performance": 0,
        "aliases": [("锦纶11", "colloquial"), ("Rilsan", "trade_name"), ("蓖麻尼龙", "colloquial"), ("PA11", "iso_code")],
        "standards": [("ISO", "ISO 2076:2021", "Polyamide")]
    },
    {
        "category_code": "SYN_PA",
        "code": "PA46",
        "name_zh": "聚酰胺46纤维 (锦纶46)",
        "name_en": "Polyamide 46 Fiber (Nylon 46)",
        "chemical_name": "聚己二酰丁二胺",
        "chemical_formula": "[-NH-(CH2)4-NH-CO-(CH2)4-CO-]n",
        "cas_number": "50327-22-5",
        "generation": "第3代耐热工程合成纤维",
        "discovery_year": "1977",
        "commercial_year": "1984",
        "pioneering_entity": "DSM (帝斯曼 / Envalior Stanyl)",
        "spinning_method": "高温熔融纺丝及固相后聚合",
        "density_g_cm3": 1.18,
        "tensile_strength_cn_dtex": 8.0,
        "tensile_strength_gpa": 0.94,
        "tensile_modulus_gpa": 7.0,
        "elongation_at_break_pct": 18.0,
        "moisture_regain_pct": 3.8,
        "loi_pct": 23.0,
        "melting_point_c": 295.0,
        "max_service_temp_c": 160.0,
        "typical_applications": "高热负荷汽车引擎舱传动皮带帘线、耐高温工业过滤毡、航空发动机密封增强织物",
        "representative_brands": "Stanyl (斯泰尼尔)",
        "tech_status_2026": "耐热蠕变与耐疲劳性能卓越，在新能源电驱系统高转速耐磨增强织物中获得新拓展",
        "is_bio_based": 0,
        "is_biodegradable": 0,
        "is_high_performance": 1,
        "aliases": [("锦纶46", "colloquial"), ("Stanyl", "trade_name"), ("PA46", "iso_code")],
        "standards": [("ASTM", "ASTM D885", "Testing Industrial Polyamides")]
    },

    # ==================== 6. 聚丙烯腈系纤维 (SYN_PAN) ====================
    {
        "category_code": "SYN_PAN",
        "code": "PAN",
        "name_zh": "聚丙烯腈纤维 (腈纶/人造羊毛)",
        "name_en": "Polyacrylonitrile Fiber (Acrylic Fiber)",
        "chemical_name": "丙烯腈多元共聚物 (丙烯腈含量>85%)",
        "chemical_formula": "[-CH2-CH(CN)-]n",
        "cas_number": "25014-41-9",
        "generation": "第1代大宗合成纤维",
        "discovery_year": "1942",
        "commercial_year": "1950",
        "pioneering_entity": "DuPont (杜邦 Orlon / 奥纶)",
        "spinning_method": "湿法或干法纺丝 (DMF、DMAc或NaSCN水溶液溶解喷丝)",
        "density_g_cm3": 1.18,
        "tensile_strength_cn_dtex": 3.2,
        "tensile_strength_gpa": 0.38,
        "tensile_modulus_gpa": 6.5,
        "elongation_at_break_pct": 30.0,
        "moisture_regain_pct": 2.0,
        "loi_pct": 18.0,
        "melting_point_c": None, # 加热热分解
        "max_service_temp_c": 125.0,
        "typical_applications": "羊毛衫毛线、毛毯人造毛皮、户外遮阳篷帆布、高耐日晒篷布、碳纤维原丝前驱体",
        "representative_brands": "Orlon (奥纶), Dralon (德绒), 抚顺腈纶, 吉林化纤腈纶",
        "tech_status_2026": "民用以超细旦高蓬松发热保暖(德绒品类)为主，高端转向大丝束高质量碳纤维原丝配套",
        "is_bio_based": 0,
        "is_biodegradable": 0,
        "is_high_performance": 0,
        "aliases": [("腈纶", "colloquial"), ("人造羊毛", "colloquial"), ("Orlon", "trade_name"), ("Dralon", "trade_name"), ("PAN", "iso_code")],
        "standards": [("GB", "GB/T 4146.1-2020", "聚丙烯腈纤维"), ("ISO", "ISO 2076:2021", "Acrylic")]
    },
    {
        "category_code": "SYN_PAN",
        "code": "MAC",
        "name_zh": "改性聚丙烯腈纤维 (变性腈纶/阻燃腈纶)",
        "name_en": "Modacrylic Fiber",
        "chemical_name": "丙烯腈与偏二氯乙烯或氯乙烯共聚物 (丙烯腈含量35%~85%)",
        "chemical_formula": "[-CH2-CH(CN)-]x-[-CH2-CCl2-]y",
        "cas_number": "26877-39-4",
        "generation": "第2代本质阻燃差别化合成纤维",
        "discovery_year": "1949",
        "commercial_year": "1950s",
        "pioneering_entity": "Union Carbide (Dynel) / 钟渊化学 (Kaneka)",
        "spinning_method": "湿法或干法纺丝 (丙酮或DMF溶剂溶解)",
        "density_g_cm3": 1.37,
        "tensile_strength_cn_dtex": 2.8,
        "tensile_strength_gpa": 0.38,
        "tensile_modulus_gpa": 5.0,
        "elongation_at_break_pct": 32.0,
        "moisture_regain_pct": 2.5,
        "loi_pct": 31.0, # 极高阻燃性，离开火焰即自熄
        "melting_point_c": None,
        "max_service_temp_c": 110.0,
        "typical_applications": "高级逼真阻燃假发、电力冶金电弧防护工服、民航阻燃毛毯、酒店防火窗帘面料",
        "representative_brands": "Kanecaron (钟化假发丝/阻燃丝), Protex",
        "tech_status_2026": "全球高端假发与安全防护面料的核心支柱原料，无锑环保阻燃与高耐热卷曲工艺普及",
        "is_bio_based": 0,
        "is_biodegradable": 0,
        "is_high_performance": 0,
        "aliases": [("变性腈纶", "colloquial"), ("阻燃腈纶", "colloquial"), ("Kanecaron", "trade_name"), ("MAC", "iso_code")],
        "standards": [("GB", "GB/T 4146.1-2020", "改性聚丙烯腈纤维"), ("ISO", "ISO 2076:2021", "Modacrylic")]
    },

    # ==================== 7. 聚烯烃系合成纤维 (SYN_PO) ====================
    {
        "category_code": "SYN_PO",
        "code": "PP",
        "name_zh": "聚丙烯纤维 (丙纶)",
        "name_en": "Polypropylene Fiber",
        "chemical_name": "等规聚丙烯",
        "chemical_formula": "[-CH2-CH(CH3)-]n",
        "cas_number": "9003-07-0",
        "generation": "第1代大宗合成纤维 (所有商业合成纤维中密度最低)",
        "discovery_year": "1954",
        "commercial_year": "1957",
        "pioneering_entity": "Giulio Natta (纳塔 / 意大利 Montecatini)",
        "spinning_method": "熔体纺丝 (熔融纺丝牵伸、纺粘法Spunbond、熔喷法Meltblown)",
        "density_g_cm3": 0.91, # 漂浮于水面
        "tensile_strength_cn_dtex": 5.0,
        "tensile_strength_gpa": 0.45,
        "tensile_modulus_gpa": 4.0,
        "elongation_at_break_pct": 28.0,
        "moisture_regain_pct": 0.05, # 近乎不吸水，单向导湿
        "loi_pct": 18.0,
        "melting_point_c": 168.0,
        "max_service_temp_c": 95.0,
        "typical_applications": "医用外科口罩及防护服熔喷过滤层、土工布、包装集装袋、速干贴身排汗运动衣",
        "representative_brands": "Herculon, Meraklon, 蒙特卡蒂尼丙纶",
        "tech_status_2026": "超细熔喷驻极体寿命突破5年，超细旦微孔丙纶在单向速干运动服与纸尿裤无纺布上深度普及",
        "is_bio_based": 0,
        "is_biodegradable": 0,
        "is_high_performance": 0,
        "aliases": [("丙纶", "colloquial"), ("聚丙烯短纤", "standard_name"), ("PP", "iso_code")],
        "standards": [("GB", "GB/T 4146.1-2020", "聚丙烯纤维"), ("ISO", "ISO 2076:2021", "Polypropylene")]
    },
    {
        "category_code": "SYN_PO",
        "code": "PE-REG",
        "name_zh": "普通聚乙烯纤维 (普通乙纶)",
        "name_en": "Polyethylene Fiber (Conventional)",
        "chemical_name": "高密度聚乙烯 (HDPE)",
        "chemical_formula": "[-CH2-CH2-]n",
        "cas_number": "9002-88-4",
        "generation": "第1代通用合成纤维",
        "discovery_year": "1933",
        "commercial_year": "1940s",
        "pioneering_entity": "ICI / 齐格勒",
        "spinning_method": "熔融纺丝 (常规单丝或扁丝挤出)",
        "density_g_cm3": 0.95,
        "tensile_strength_cn_dtex": 3.5,
        "tensile_strength_gpa": 0.33,
        "tensile_modulus_gpa": 2.5,
        "elongation_at_break_pct": 25.0,
        "moisture_regain_pct": 0.01,
        "loi_pct": 17.5,
        "melting_point_c": 130.0,
        "max_service_temp_c": 80.0,
        "typical_applications": "农业遮阳网、防虫网、浅海渔网绳缆、编织袋、人工草坪草丝",
        "representative_brands": "Courlene, Polythene filament",
        "tech_status_2026": "抗紫外UV老化母粒配方与长寿命抗刮擦草丝技术高度成熟",
        "is_bio_based": 0,
        "is_biodegradable": 0,
        "is_high_performance": 0,
        "aliases": [("乙纶", "colloquial"), ("聚乙烯纤维", "standard_name"), ("PE", "iso_code")],
        "standards": [("GB", "GB/T 4146.1-2020", "聚乙烯纤维"), ("ISO", "ISO 2076:2021", "Polyethylene")]
    },
    {
        "category_code": "SYN_PO",
        "code": "PMP",
        "name_zh": "聚4-甲基-1-戊烯纤维 (TPX纤维)",
        "name_en": "Poly(4-methyl-1-pentene) Fiber",
        "chemical_name": "聚(4-甲基-1-戊烯)",
        "chemical_formula": "[-CH2-CH(CH2CH(CH3)2)-]n",
        "cas_number": "25068-26-2",
        "generation": "第3代特种耐热聚烯烃纤维",
        "discovery_year": "1965",
        "commercial_year": "1975",
        "pioneering_entity": "ICI / 三井化学 (Mitsui TPX)",
        "spinning_method": "熔融纺丝与高倍拉伸",
        "density_g_cm3": 0.83, # 现存最轻的结晶聚合物纤维之一
        "tensile_strength_cn_dtex": 4.5,
        "tensile_strength_gpa": 0.37,
        "tensile_modulus_gpa": 3.8,
        "elongation_at_break_pct": 22.0,
        "moisture_regain_pct": 0.01,
        "loi_pct": 18.0,
        "melting_point_c": 240.0, # 远超普通PP和PE
        "max_service_temp_c": 140.0,
        "typical_applications": "超轻离型织物、医疗透析空心纤维膜、超轻高绝缘电缆绕包层、微波加热容器滤布",
        "representative_brands": "TPX (三井化学)",
        "tech_status_2026": "凭借极低介电常数(Dk≈2.1)和优异透气耐温性，在6G高频通信及特种分离膜稳步放量",
        "is_bio_based": 0,
        "is_biodegradable": 0,
        "is_high_performance": 1,
        "aliases": [("TPX", "trade_name"), ("PMP", "abbreviation")],
        "standards": [("ASTM", "ASTM D4101", "Propylene Plastic Injection and Extrusion Materials")]
    },

    # ==================== 8. 聚氨酯与弹性纤维 (SYN_PU) ====================
    {
        "category_code": "SYN_PU",
        "code": "EL",
        "name_zh": "聚氨酯弹性纤维 (氨纶/斯潘德克斯)",
        "name_en": "Elastane / Spandex Fiber",
        "chemical_name": "聚氨基甲酸酯嵌段共聚物 (聚醚/聚酯软段与二异氰酸酯硬段)",
        "chemical_formula": "[-O-R-O-CONH-R'-NHCO-]n",
        "cas_number": "61788-20-7",
        "generation": "第2代合成弹性高分子",
        "discovery_year": "1952",
        "commercial_year": "1959",
        "pioneering_entity": "Joseph Shivers (杜邦 DuPont Lycra / 莱卡)",
        "spinning_method": "干法纺丝 (DMAC溶液挤入高温氮气甬道)、少部分熔融纺丝或湿纺",
        "density_g_cm3": 1.21,
        "tensile_strength_cn_dtex": 1.1,
        "tensile_strength_gpa": 0.13,
        "tensile_modulus_gpa": 0.05,
        "elongation_at_break_pct": 520.0,
        "moisture_regain_pct": 1.1,
        "loi_pct": 18.0,
        "melting_point_c": 230.0,
        "max_service_temp_c": 110.0,
        "typical_applications": "瑜伽服、游泳衣、紧身牛仔裤、运动功能压缩衣、高档贴身无缝内衣、纸尿裤防漏边",
        "representative_brands": "Lycra (莱卡), Creora (晓星), 华峰千禧氨纶",
        "tech_status_2026": "生物基BDO原料氨纶(生物基含量超70%)与低温可热熔粘合氨纶成为产业升级核心",
        "is_bio_based": 0,
        "is_biodegradable": 0,
        "is_high_performance": 0,
        "aliases": [("氨纶", "colloquial"), ("Spandex", "trade_name"), ("Lycra", "trade_name"), ("莱卡", "trade_name"), ("EL", "iso_code")],
        "standards": [("GB", "GB/T 4146.1-2020", "氨纶定义"), ("ISO", "ISO 2076:2021", "Elastane")]
    },
    {
        "category_code": "SYN_PU",
        "code": "TPU-F",
        "name_zh": "热塑性聚氨酯弹性纤维 (熔纺TPU纤维)",
        "name_en": "Thermoplastic Polyurethane Fiber",
        "chemical_name": "热塑性聚氨酯弹性体 (TPU)",
        "chemical_formula": "Thermoplastic Polyurethane",
        "cas_number": "61788-20-7",
        "generation": "第3代绿色无溶剂弹性纤维",
        "discovery_year": "1980s",
        "commercial_year": "2000s",
        "pioneering_entity": "BASF (巴斯夫) / Lubrizol (路博润) / 万华化学",
        "spinning_method": "环保无溶剂熔融纺丝法 (无需DMF/DMAC，环境极度友好)",
        "density_g_cm3": 1.18,
        "tensile_strength_cn_dtex": 1.6,
        "tensile_strength_gpa": 0.19,
        "tensile_modulus_gpa": 0.08,
        "elongation_at_break_pct": 450.0,
        "moisture_regain_pct": 0.8,
        "loi_pct": 20.0,
        "melting_point_c": 195.0,
        "max_service_temp_c": 115.0,
        "typical_applications": "飞织一体鞋面、单一材质100%可循环运动服、弹性无缝粘合线、防水透气弹性复合膜",
        "representative_brands": "Elastollan (巴斯夫), 万华TPU熔纺纤维",
        "tech_status_2026": "配合单一材质闭环回收(Mono-material design)浪潮，全面替代传统化学溶剂干法氨纶鞋服配件",
        "is_bio_based": 0,
        "is_biodegradable": 0,
        "is_high_performance": 0,
        "aliases": [("TPU纤维", "abbreviation"), ("熔纺氨纶", "colloquial")],
        "standards": [("GB", "FZ/T 54101-2017", "热塑性聚氨酯弹性长丝")]
    },

    # ==================== 9. 聚乙烯醇系合成纤维 (SYN_PVA) ====================
    {
        "category_code": "SYN_PVA",
        "code": "PVA-F",
        "name_zh": "聚乙烯醇缩甲醛纤维 (维纶/维尼纶)",
        "name_en": "Vinylon / Polyvinyl Alcohol Formalized Fiber",
        "chemical_name": "聚乙烯醇缩甲醛化共聚物",
        "chemical_formula": "[-CH2-CH(OH)-]x-[-CH2-CH(O-CH2-O)CH-]y",
        "cas_number": "25067-34-9",
        "generation": "第1代大宗合成纤维",
        "discovery_year": "1939",
        "commercial_year": "1950",
        "pioneering_entity": "李升基 (中国/朝鲜科学家) / 樱田一郎 (日本可乐丽 Kuraray)",
        "spinning_method": "湿法或干法纺丝 (PVA水溶液芒硝硫酸钠盐浴凝固，甲醛缩醛化固化交联)",
        "density_g_cm3": 1.29,
        "tensile_strength_cn_dtex": 4.5,
        "tensile_strength_gpa": 0.58,
        "tensile_modulus_gpa": 8.0,
        "elongation_at_break_pct": 20.0,
        "moisture_regain_pct": 5.0, # 合成纤维中吸湿性仅次于锦纶56
        "loi_pct": 20.0,
        "melting_point_c": 230.0,
        "max_service_temp_c": 115.0,
        "typical_applications": "高强帆布篷布、橡胶输送带骨架、耐磨军用背包帐篷、无石棉水泥增强材料",
        "representative_brands": "Kuralon (可乐丽), Vinylon, 皖维维纶",
        "tech_status_2026": "作为环保代石棉增强纤维在建筑纤维水泥板(FRC)中具有刚性不可替代全球市场",
        "is_bio_based": 0,
        "is_biodegradable": 0,
        "is_high_performance": 0,
        "aliases": [("维纶", "colloquial"), ("维尼纶", "colloquial"), ("Kuralon", "trade_name"), ("PVA", "iso_code")],
        "standards": [("GB", "GB/T 4146.1-2020", "聚乙烯醇纤维"), ("ISO", "ISO 2076:2021", "Vinylal")]
    },
    {
        "category_code": "SYN_PVA",
        "code": "W-PVA",
        "name_zh": "水溶性聚乙烯醇纤维 (水溶维纶)",
        "name_en": "Water-Soluble PVA Fiber",
        "chemical_name": "未经缩醛化改性高纯聚乙烯醇",
        "chemical_formula": "[-CH2-CH(OH)-]n",
        "cas_number": "9002-89-5",
        "generation": "第2代功能差别化纤维",
        "discovery_year": "1960s",
        "commercial_year": "1970s",
        "pioneering_entity": "Kuraray (日本可乐丽) / 皖维高新",
        "spinning_method": "湿法纺丝或冻胶纺丝 (水相凝固，不经甲醛缩醛化，精准调控醇解度)",
        "density_g_cm3": 1.28,
        "tensile_strength_cn_dtex": 3.8,
        "tensile_strength_gpa": 0.48,
        "tensile_modulus_gpa": 6.5,
        "elongation_at_break_pct": 18.0,
        "moisture_regain_pct": 5.5,
        "loi_pct": 19.5,
        "melting_point_c": 220.0,
        "max_service_temp_c": 80.0, # 水溶温度可设计为20℃/40℃/70℃/90℃
        "typical_applications": "无捻毛巾骨架纱(水洗后脱除造就超蓬松触感)、水溶无纺绣花基布、医用防感染自溶隔离袋",
        "representative_brands": "Kuralon K-II, 皖维水溶纤维",
        "tech_status_2026": "低温20℃速溶且无残毒生物可降解型在高端绿色纺织与绣花耗材全面普及",
        "is_bio_based": 0,
        "is_biodegradable": 1,
        "is_high_performance": 0,
        "aliases": [("水溶维纶", "colloquial"), ("水溶纤维", "colloquial")],
        "standards": [("GB", "FZ/T 52005-2014", "水溶性聚乙烯醇短纤维")]
    },
    {
        "category_code": "SYN_PVA",
        "code": "HM-PVA",
        "name_zh": "高强高模聚乙烯醇纤维",
        "name_en": "High-Strength High-Modulus PVA Fiber",
        "chemical_name": "超高聚合度全等规/间规聚乙烯醇",
        "chemical_formula": "[-CH2-CH(OH)-]n (DP > 3500)",
        "cas_number": "9002-89-5",
        "generation": "第3代高性能特种聚合物纤维",
        "discovery_year": "1980s",
        "commercial_year": "1990s",
        "pioneering_entity": "Kuraray (可乐丽) / 中国石化四川维纶",
        "spinning_method": "凝胶冻胶纺丝-超高倍热拉伸 (DMSO或有机溶剂体系)",
        "density_g_cm3": 1.30,
        "tensile_strength_cn_dtex": 11.5,
        "tensile_strength_gpa": 1.50,
        "tensile_modulus_gpa": 35.0,
        "elongation_at_break_pct": 6.5,
        "moisture_regain_pct": 3.0,
        "loi_pct": 21.0,
        "melting_point_c": 245.0,
        "max_service_temp_c": 140.0,
        "typical_applications": "水利水电超高强工程水泥防裂筋、深海缆绳、轻量化防弹复合材料、特种高压绝缘纸",
        "representative_brands": "Kuralon II, 川维高强高模PVA",
        "tech_status_2026": "我国完全掌握万吨级高端干湿法凝胶拉伸核心技术，出口全球数十个国家基建工程",
        "is_bio_based": 0,
        "is_biodegradable": 0,
        "is_high_performance": 1,
        "aliases": [("高强高模维纶", "colloquial"), ("高模PVA", "abbreviation")],
        "standards": [("GB", "GB/T 21120-2018", "水泥混凝土和砂浆用高强高模聚乙烯醇纤维")]
    },

    # ==================== 10. 含卤素通用合成纤维 (SYN_HALO) ====================
    {
        "category_code": "SYN_HALO",
        "code": "PVC-F",
        "name_zh": "聚氯乙烯纤维 (氯纶)",
        "name_en": "Polyvinyl Chloride Fiber (Chlorofibre)",
        "chemical_name": "聚氯乙烯",
        "chemical_formula": "[-CH2-CHCl-]n",
        "cas_number": "9002-86-2",
        "generation": "第1代合成纤维 (早期与德国人造丝并驾齐驱)",
        "discovery_year": "1913",
        "commercial_year": "1934",
        "pioneering_entity": "Fritz Klatte / 德国 IG Farben (PeCe 纤维)",
        "spinning_method": "干法或湿法纺丝 (丙酮/苯溶剂)",
        "density_g_cm3": 1.40,
        "tensile_strength_cn_dtex": 2.5,
        "tensile_strength_gpa": 0.35,
        "tensile_modulus_gpa": 3.5,
        "elongation_at_break_pct": 35.0,
        "moisture_regain_pct": 0.1,
        "loi_pct": 38.0, # 极高难燃性
        "melting_point_c": None, # 80℃即软化收缩
        "max_service_temp_c": 70.0,
        "typical_applications": "极度耐酸碱耐腐蚀工业滤布、理疗静电保健内衣被褥、影剧院舞台阻燃幕布",
        "representative_brands": "Rhovyl (法国罗维尔), PeCe, 氯纶",
        "tech_status_2026": "虽然耐热性差，但利用其独特的高负摩擦静电发生性在医疗静电理疗纺织品领域持续独占鳌头",
        "is_bio_based": 0,
        "is_biodegradable": 0,
        "is_high_performance": 0,
        "aliases": [("氯纶", "colloquial"), ("Rhovyl", "trade_name"), ("PVC纤维", "abbreviation"), ("CLF", "iso_code")],
        "standards": [("GB", "GB/T 4146.1-2020", "含氯纤维"), ("ISO", "ISO 2076:2021", "Chlorofibre")]
    },
    {
        "category_code": "SYN_HALO",
        "code": "PVDC-F",
        "name_zh": "聚偏二氯乙烯纤维 (偏氯纶/莎纶)",
        "name_en": "Polyvinylidene Chloride Fiber (Saran)",
        "chemical_name": "偏二氯乙烯-氯乙烯共聚物",
        "chemical_formula": "[-CH2-CCl2-]x-[-CH2-CHCl-]y",
        "cas_number": "9002-85-1",
        "generation": "第1代耐候耐化合成纤维",
        "discovery_year": "1933",
        "commercial_year": "1940",
        "pioneering_entity": "Ralph Wiley (陶氏化学 Dow Chemical)",
        "spinning_method": "熔融挤出快速水冷淬火及冷拉伸单丝",
        "density_g_cm3": 1.70,
        "tensile_strength_cn_dtex": 2.0,
        "tensile_strength_gpa": 0.34,
        "tensile_modulus_gpa": 2.2,
        "elongation_at_break_pct": 25.0,
        "moisture_regain_pct": 0.1,
        "loi_pct": 60.0, # 极端难燃自熄
        "melting_point_c": 170.0,
        "max_service_temp_c": 85.0,
        "typical_applications": "耐日光露天沙滩椅面料、汽车阻燃座套、高档仿真发丝、强酸强碱腐蚀环境工业滤网",
        "representative_brands": "Saran (莎纶 / 陶氏)",
        "tech_status_2026": "以其卓越的超低透氧透湿性与耐候耐光老化性能，在特种户外工业织物中保持稳健需求",
        "is_bio_based": 0,
        "is_biodegradable": 0,
        "is_high_performance": 0,
        "aliases": [("偏氯纶", "colloquial"), ("莎纶", "trade_name"), ("Saran", "trade_name")],
        "standards": [("ISO", "ISO 2076:2021", "Saran definition")]
    }
]

print(f"Loaded Part 1: {len(FIBERS_PART_1)} chemical fibers.")
