# -*- coding: utf-8 -*-
"""
化学纤维数据集 Part 3:
5. 碳纤维及先进碳基纤维 (CARBON: PAN-CF, Pitch-CF, Rayon-CF, ACF, CNT, Graphene)
6. 无机非金属与金属化学纤维 (INORGANIC: 玻纤体系、玄武岩纤维、陶瓷纤维SiC/氧化铝/氮化硅/硼、金属丝及液态金属)
7. 前沿智能、仿生与生物工程纤维 (EMERGING 2026: 重组蜘蛛丝、气凝胶纤维、MXene、纤维电池、相变纤维、TENG等)
"""

FIBERS_PART_3 = [
    # ==================== 1. 碳纤维及先进碳基纤维 (CARBON) ====================
    {
        "category_code": "CF_PAN",
        "code": "PAN-CF-HS",
        "name_zh": "聚丙烯腈基高强型碳纤维 (T300/T700/T800/T1000/T1100)",
        "name_en": "PAN-based High-Strength Carbon Fiber",
        "chemical_name": "聚丙烯腈热解乱层石墨微晶连续纤维",
        "chemical_formula": "C (Carbon content > 93-95%)",
        "cas_number": "7440-44-0",
        "generation": "第3代现代工业黑色黄金",
        "discovery_year": "1959",
        "commercial_year": "1971",
        "pioneering_entity": "Akio Shindo (进藤昭男 / 日本产总研) / 日本东丽 (Toray Torayca)",
        "spinning_method": "湿法或干喷湿纺制备高纯原丝，经预氧化(200-300℃)、高温炭化(1000-1500℃)惰性气氛热解",
        "density_g_cm3": 1.79,
        "tensile_strength_cn_dtex": 31.0,
        "tensile_strength_gpa": 5.50, # T800/T1000级可达 5.5~7.0 GPa
        "tensile_modulus_gpa": 290.0,
        "elongation_at_break_pct": 1.9,
        "moisture_regain_pct": 0.0,
        "loi_pct": 65.0, # 极难燃烧，耐惰性高温超2000℃
        "melting_point_c": None, # 3600℃升华
        "max_service_temp_c": 500.0, # 空气中有氧氧化温度约400-500℃，无氧超2000℃
        "typical_applications": "军用民用先进大飞机机身(波音787/空客A350/C929)、风力发电超长叶片碳梁、氢气瓶III/IV型缠绕层、高端体育器材",
        "representative_brands": "Torayca T700/T800/T1100, 中复神鹰 SYT55S, 光威复材, 恒神",
        "tech_status_2026": "我国T700/T800万吨级工程化全面成熟并占领全球主导，高强高模兼备高延伸T1100G/T1200级在尖端国防批量装备",
        "is_bio_based": 0,
        "is_biodegradable": 0,
        "is_high_performance": 1,
        "aliases": [("碳纤维", "colloquial"), ("T700", "trade_name"), ("T800", "trade_name"), ("T1000", "trade_name"), ("Torayca", "trade_name"), ("CF", "abbreviation")],
        "standards": [("GB", "GB/T 26752-2020", "聚丙烯腈基碳纤维"), ("ISO", "ISO 13002", "Carbon fibre - Determination of filament diameter")]
    },
    {
        "category_code": "CF_PAN",
        "code": "PAN-CF-HM",
        "name_zh": "聚丙烯腈基高模/超高模型碳纤维 (M40/M55/M60/M65J)",
        "name_en": "PAN-based High-Modulus Carbon Fiber",
        "chemical_name": "超高温石墨化微晶规整排布碳纤维",
        "chemical_formula": "C (Carbon content > 99%)",
        "cas_number": "7440-44-0",
        "generation": "第4代超刚性宇航级石墨纤维",
        "discovery_year": "1970s",
        "commercial_year": "1980s",
        "pioneering_entity": "Toray (日本东丽) / Hexcel (美国赫氏)",
        "spinning_method": "经超高温石墨化炉(2000-3000℃)超高温热处理，诱导微晶高度三维石墨化生长取向",
        "density_g_cm3": 1.93,
        "tensile_strength_cn_dtex": 19.5,
        "tensile_strength_gpa": 3.80,
        "tensile_modulus_gpa": 588.0, # 模量逼近600 GPa，提供近乎零热膨胀超高刚性
        "elongation_at_break_pct": 0.6, # 极低断裂延伸率，高刚性
        "moisture_regain_pct": 0.0,
        "loi_pct": 70.0,
        "melting_point_c": None,
        "max_service_temp_c": 500.0,
        "typical_applications": "天宫空间站柔性太阳翼支撑桁架、高精度对地遥感卫星相机镜头筒、洲际弹道导弹控制舵面、离子发动机栅极",
        "representative_brands": "Torayca M40J / M55J / M60J, 光威复材QM40/QM55",
        "tech_status_2026": "实现M55J与M60J百吨级完全自主供应链，突破极低线膨胀系数控制，保障国家天基光学与深空探测关键指标",
        "is_bio_based": 0,
        "is_biodegradable": 0,
        "is_high_performance": 1,
        "aliases": [("高模碳纤维", "colloquial"), ("石墨纤维", "colloquial"), ("M55J", "trade_name"), ("M60J", "trade_name")],
        "standards": [("GB", "GB/T 30019-2013", "碳纤维 密度的测定"), ("ISO", "ISO 10119", "Carbon fibre - Determination of density")]
    },
    {
        "category_code": "CF_PITCH",
        "code": "PITCH-CF",
        "name_zh": "沥青基碳纤维 (中间相超高模/各向同性级)",
        "name_en": "Pitch-based Carbon Fiber (Mesophase & Isotropic)",
        "chemical_name": "中间相沥青缩聚石墨化碳纤维",
        "chemical_formula": "C (Carbon content > 99.5%)",
        "cas_number": "7440-44-0",
        "generation": "第3代超高导热超高刚度特种碳纤维",
        "discovery_year": "1963",
        "commercial_year": "1970s",
        "pioneering_entity": "Otani (大谷杉郎) / Union Carbide / 日本三菱化学 (DIALEAD)",
        "spinning_method": "煤或石油沥青经精制形成向列型中间相液晶沥青，熔融微孔纺丝、不熔化预氧化及超高温石墨化",
        "density_g_cm3": 2.20,
        "tensile_strength_cn_dtex": 16.0,
        "tensile_strength_gpa": 3.40,
        "tensile_modulus_gpa": 900.0, # 模量高达900 GPa（钢铁的4.5倍），热导率达1000 W/m·K（铜的2.5倍）
        "elongation_at_break_pct": 0.4,
        "moisture_regain_pct": 0.0,
        "loi_pct": 75.0,
        "melting_point_c": None,
        "max_service_temp_c": 550.0,
        "typical_applications": "高功率卫星电子芯片超高导热散热基板、宇航飞行器主结构、极端超高刚性空间天线反射器",
        "representative_brands": "DIALEAD (三菱化学), Granoc (日本新日铁), 湖南大学沥青基CF",
        "tech_status_2026": "超高导热中间相沥青基碳纤维全面打破国际技术封锁，实现百吨级高纯连续丝稳定生产",
        "is_bio_based": 0,
        "is_biodegradable": 0,
        "is_high_performance": 1,
        "aliases": [("沥青基碳纤维", "colloquial"), ("中间相碳纤维", "colloquial"), ("DIALEAD", "trade_name")],
        "standards": [("GB", "GB/T 36769-2018", "沥青基碳纤维")]
    },
    {
        "category_code": "CF_RAYON",
        "code": "RAYON-CF",
        "name_zh": "粘胶基碳纤维 (宇航防热烧蚀碳纤维)",
        "name_en": "Rayon-based Carbon Fiber",
        "chemical_name": "人造纤维素裂解无定形多孔微晶碳纤维",
        "chemical_formula": "C (Carbon content 90~98%)",
        "cas_number": "7440-44-0",
        "generation": "第1代航天特种碳纤维",
        "discovery_year": "1879",
        "commercial_year": "1950s",
        "pioneering_entity": "Thomas Edison (爱迪生竹丝/人造丝炭化) / 联合碳化物 (Union Carbide UCC)",
        "spinning_method": "高品质粘胶平纹布/长丝经阻燃浸渍催化、阶梯式慢速脱水预氧化及1200℃热解炭化",
        "density_g_cm3": 1.45,
        "tensile_strength_cn_dtex": 5.5,
        "tensile_strength_gpa": 0.80, # 力学强度不及PAN基，但具有极低的热导率与优异石墨化烧蚀稳定性
        "tensile_modulus_gpa": 45.0,
        "elongation_at_break_pct": 2.0,
        "moisture_regain_pct": 1.0,
        "loi_pct": 60.0,
        "melting_point_c": None,
        "max_service_temp_c": 600.0, # 宇航短时耐3000℃等离子体冲刷
        "typical_applications": "洲际导弹再入弹头端头防热帽、固体火箭发动机喷管喉衬喉栓、高超音速飞行器防热大底烧蚀部件",
        "representative_brands": "AvCarb, UCC Thornel-25, 航天材料及工艺研究所粘胶基CF",
        "tech_status_2026": "作为国家级不可替代的极端耐烧蚀隔热特种战略物资，连续化催化低温预氧化技术大幅提高成品率",
        "is_bio_based": 1,
        "is_biodegradable": 0,
        "is_high_performance": 1,
        "aliases": [("粘胶基碳纤维", "colloquial"), ("烧蚀防热碳纤维", "colloquial")],
        "standards": [("GJB", "GJB 7234-2011", "固体火箭发动机喷管用粘胶基碳布规范")]
    },
    {
        "category_code": "CF_ACT",
        "code": "ACF",
        "name_zh": "活性碳纤维 (ACF/微孔吸附纤维)",
        "name_en": "Activated Carbon Fiber",
        "chemical_name": "富微孔高比表面积石墨化交联碳纤维",
        "chemical_formula": "C (Micro-porous Carbon)",
        "cas_number": "7440-44-0",
        "generation": "第2代吸附分离功能纤维",
        "discovery_year": "1960s",
        "commercial_year": "1970s",
        "pioneering_entity": "Brimer / 日本可乐丽 (Kuraray) / 东洋纺",
        "spinning_method": "粘胶、酚醛或PAN纤维碳化后，在800-1000℃经水蒸气或CO2高温物理/化学活化造孔",
        "density_g_cm3": 0.85,
        "tensile_strength_cn_dtex": 2.5,
        "tensile_strength_gpa": 0.25,
        "tensile_modulus_gpa": 15.0,
        "elongation_at_break_pct": 2.5,
        "moisture_regain_pct": 3.0,
        "loi_pct": 50.0,
        "melting_point_c": None,
        "max_service_temp_c": 350.0,
        "typical_applications": "化生核防毒面具滤芯、半导体超纯VOC有机废气脱附回收装置、血液透析吸附净化滤柱、超级电容器电极",
        "representative_brands": "Kynol ACF, Kuractive, 赛普乐斯ACF",
        "tech_status_2026": "微孔比表面积突破2500 m²/g且孔径分布在1-2 nm均匀调控，吸脱附速率较传统颗粒活性炭快数十倍",
        "is_bio_based": 0,
        "is_biodegradable": 0,
        "is_high_performance": 1,
        "aliases": [("活性碳纤维", "colloquial"), ("ACF", "abbreviation"), ("碳吸附纤维", "colloquial")],
        "standards": [("GB", "GB/T 32993-2016", "活性碳纤维微孔孔径分布测定")]
    },
    {
        "category_code": "CF_NANO",
        "code": "CNT-F",
        "name_zh": "碳纳米管宏观连续纤维 (CNT纤维)",
        "name_en": "Carbon Nanotube Fiber (CNT Fiber)",
        "chemical_name": "高度取向密排单壁/双壁碳纳米管宏观聚集体长丝",
        "chemical_formula": "C (Single/Few-walled CNT arrays)",
        "cas_number": "308068-56-6",
        "generation": "第4代纳米尺度宏观组装尖端纤维",
        "discovery_year": "2000",
        "commercial_year": "2015",
        "pioneering_entity": "Poulin (湿法纺丝) / Windle (剑桥大学浮动催化CVD) / 魏飞 (清华) / 中科院物理所",
        "spinning_method": "浮动催化化学气相沉积(FCCVD)气相直接牵伸卷绕纺丝，或超强酸液晶湿法纺丝",
        "density_g_cm3": 1.40,
        "tensile_strength_cn_dtex": 32.0,
        "tensile_strength_gpa": 4.50, # 实验室纪录已破10 GPa
        "tensile_modulus_gpa": 250.0,
        "elongation_at_break_pct": 4.5,
        "moisture_regain_pct": 0.1,
        "loi_pct": 60.0,
        "melting_point_c": None,
        "max_service_temp_c": 450.0,
        "typical_applications": "卫星微波同轴电缆轻量化屏蔽网织物(减重80%)、宇航航天抗雷击网、微型智能肌肉驱动线、可穿戴电热防除冰",
        "representative_brands": "Tortech Nano, Nanocomp DexMat Galvorn, 碳纳米管连续纺丝",
        "tech_status_2026": "千米级连续原位纺丝速率突破100 m/min，导电率逼近金属铜(>10^7 S/m)，在航空航天线束轻量化大规模替代铜网",
        "is_bio_based": 0,
        "is_biodegradable": 0,
        "is_high_performance": 1,
        "aliases": [("CNT纤维", "abbreviation"), ("碳纳米管长丝", "colloquial"), ("Galvorn", "trade_name")],
        "standards": [("ISO", "ISO/TS 10798", "Nanotechnologies - Characterization of single-wall carbon nanotubes using SEM and EDX")]
    },
    {
        "category_code": "CF_NANO",
        "code": "GF-NANO",
        "name_zh": "石墨烯宏观连续纤维 (石墨烯长丝)",
        "name_en": "Graphene Fiber",
        "chemical_name": "二维石墨烯片层高度沿轴向排列组装宏观长丝",
        "chemical_formula": "C (Reduced Graphene Oxide / Neat Graphene)",
        "cas_number": "1034343-98-0",
        "generation": "第4代纳米材料宏观有序构筑纤维",
        "discovery_year": "2011",
        "commercial_year": "2020",
        "pioneering_entity": "高超 (浙江大学高分子系团队原创发明)",
        "spinning_method": "氧化石墨烯高浓度液晶溶液湿法纺丝，经化学还原/高温热还原深度石墨化缺陷修复",
        "density_g_cm3": 1.65,
        "tensile_strength_cn_dtex": 22.0,
        "tensile_strength_gpa": 3.60,
        "tensile_modulus_gpa": 400.0,
        "elongation_at_break_pct": 2.0,
        "moisture_regain_pct": 0.2,
        "loi_pct": 65.0,
        "melting_point_c": None,
        "max_service_temp_c": 500.0,
        "typical_applications": "极端高导热热沉织物、柔性超级电容器电极核心丝、高灵敏智能生理信号传感纤维、抗辐射特种导线",
        "representative_brands": "高超团队石墨烯长丝, 杭州高烯科技",
        "tech_status_2026": "实现百吨级多孔高强石墨烯导电导热纤维量产，热导率达1500 W/m·K，在下一代大功率柔性可穿戴热管理商业化落地",
        "is_bio_based": 0,
        "is_biodegradable": 0,
        "is_high_performance": 1,
        "aliases": [("石墨烯纤维", "colloquial"), ("GF", "abbreviation")],
        "standards": [("GB", "GB/T 30544.13-2018", "纳米科技 术语 第13部分：石墨烯及相关二维材料")]
    },

    # ==================== 2. 高性能玻璃纤维系列 (INORG_GLASS) ====================
    {
        "category_code": "INORG_GLASS",
        "code": "E-GLASS",
        "name_zh": "无碱玻璃纤维 (E-玻纤)",
        "name_en": "Alkali-free Glass Fiber (E-Glass)",
        "chemical_name": "铝硼硅酸盐玻璃 (碱金属氧化物<0.8%)",
        "chemical_formula": "SiO2-Al2O3-B2O3-CaO-MgO",
        "cas_number": "65997-17-3",
        "generation": "第1代无机基础复合增强纤维",
        "discovery_year": "1930s",
        "commercial_year": "1938",
        "pioneering_entity": "Owens-Corning (欧文斯科宁) / 中国巨石",
        "spinning_method": "单元池窑拉丝法 (玻璃配合料1580℃高温熔融，铂铑合金多孔漏板高速下拉卷绕)",
        "density_g_cm3": 2.58,
        "tensile_strength_cn_dtex": 13.5,
        "tensile_strength_gpa": 3.40,
        "tensile_modulus_gpa": 76.0,
        "elongation_at_break_pct": 4.5,
        "moisture_regain_pct": 0.0,
        "loi_pct": 100.0, # 纯无机，绝对不燃
        "melting_point_c": 1200.0, # 软化点约840℃
        "max_service_temp_c": 550.0,
        "typical_applications": "风电叶片、覆铜板PCB基板增强布、汽车轻量化SMC/BMC模塑料、玻璃钢游艇、建筑防腐管道",
        "representative_brands": "Advantex, 中国巨石E6/E7/E8, 泰山玻纤, 重庆国际",
        "tech_status_2026": "中国产能占全球75%以上；高模低能耗无硼无氟配方（模量破90 GPa）成为大型化百米风电叶片标配",
        "is_bio_based": 0,
        "is_biodegradable": 0,
        "is_high_performance": 0,
        "aliases": [("E玻纤", "abbreviation"), ("无碱玻纤", "colloquial"), ("玻璃纤维", "standard_name")],
        "standards": [("GB", "GB/T 18369-2008", "玻璃纤维无捻粗纱"), ("ISO", "ISO 2076:2021", "Glass generic name")]
    },
    {
        "category_code": "INORG_GLASS",
        "code": "S-GLASS",
        "name_zh": "高强高模玻璃纤维 (S-Glass / S-2 Glass)",
        "name_en": "High-Strength Glass Fiber (S-Glass)",
        "chemical_name": "无硼镁铝硅酸盐玻璃",
        "chemical_formula": "SiO2-Al2O3-MgO ternary system",
        "cas_number": "65997-17-3",
        "generation": "第2代特种军工级高强玻纤",
        "discovery_year": "1960s",
        "commercial_year": "1968",
        "pioneering_entity": "Owens-Corning (S-2 Glass) / 南京玻璃纤维研究设计院 (中材科技)",
        "spinning_method": "超高温池窑/贵金属坩埚拉丝 (熔化温度>1650℃)",
        "density_g_cm3": 2.48,
        "tensile_strength_cn_dtex": 18.5,
        "tensile_strength_gpa": 4.60, # 强度较E玻纤提升40%以上
        "tensile_modulus_gpa": 89.0,
        "elongation_at_break_pct": 5.2,
        "moisture_regain_pct": 0.0,
        "loi_pct": 100.0,
        "melting_point_c": 1450.0, # 软化点达1050℃
        "max_service_temp_c": 750.0,
        "typical_applications": "武装直升机防弹装甲座舱板、大型火箭复合材料压力容器、步兵战车轻量化防破片衬层、高抗冲机翼天线罩",
        "representative_brands": "S-2 Glass, HS4/HS6 (中材科技南玻院)",
        "tech_status_2026": "国内新一代模量达100 GPa超高强玻纤打破国际垄断，在深潜器耐压球壳与重型装备结构件广泛装配",
        "is_bio_based": 0,
        "is_biodegradable": 0,
        "is_high_performance": 1,
        "aliases": [("S玻纤", "abbreviation"), ("S-2玻纤", "trade_name"), ("高强玻璃纤维", "standard_name")],
        "standards": [("GB", "GB/T 30022-2013", "高强玻璃纤维无捻粗纱")]
    },
    {
        "category_code": "INORG_GLASS",
        "code": "QUARTZ-F",
        "name_zh": "高纯石英纤维 (石英玻璃纤维)",
        "name_en": "Quartz Fiber (High Purity Fused Silica Fiber)",
        "chemical_name": "超纯熔融二氧化硅 (SiO2纯度>99.95%)",
        "chemical_formula": "SiO2 (>99.95%)",
        "cas_number": "60676-86-0",
        "generation": "第3代极限耐高温低介电特种无机纤维",
        "discovery_year": "1950s",
        "commercial_year": "1960s",
        "pioneering_entity": "Saint-Gobain (圣戈班 Quartzel) / 菲利华 (Feilihua)",
        "spinning_method": "天然高纯水晶棒经氢氧焰或等离子焰高温熔化拉丝",
        "density_g_cm3": 2.20,
        "tensile_strength_cn_dtex": 16.0,
        "tensile_strength_gpa": 3.60,
        "tensile_modulus_gpa": 78.0,
        "elongation_at_break_pct": 4.6,
        "moisture_regain_pct": 0.0,
        "loi_pct": 100.0,
        "melting_point_c": 1700.0, # 长期耐1050℃，瞬时耐温超1500℃
        "max_service_temp_c": 1050.0,
        "typical_applications": "超高音速战机/导弹雷达透波天线罩(极低介电常数Dk=3.74, 损耗Df=0.0002)、航天飞机防热瓦隔热层、半导体石英织物",
        "representative_brands": "Quartzel (圣戈班), 菲利华石英纤维",
        "tech_status_2026": "掌握超纯合成二氧化硅棒材气相沉积拉丝新工艺，纯度达99.999%且耐辐照无色心，全面装备国家重点航天型号",
        "is_bio_based": 0,
        "is_biodegradable": 0,
        "is_high_performance": 1,
        "aliases": [("石英纤维", "colloquial"), ("Quartzel", "trade_name"), ("二氧化硅纤维", "chemical_name")],
        "standards": [("JC", "JC/T 584-2016", "石英玻璃纤维")]
    },
    {
        "category_code": "INORG_GLASS",
        "code": "LOW-DK-G",
        "name_zh": "低介电超薄玻璃纤维 (Low-Dk玻纤)",
        "name_en": "Low Dielectric Glass Fiber (Low-Dk / Low-Df)",
        "chemical_name": "低介电硼硅酸盐特种玻璃",
        "chemical_formula": "SiO2-B2O3-Al2O3 Low-loss Glass",
        "cas_number": "65997-17-3",
        "generation": "第4代高频高速通信电子特种纤维",
        "discovery_year": "2000s",
        "commercial_year": "2018",
        "pioneering_entity": "AGC (旭硝子) / 宏和科技 / 中国巨石",
        "spinning_method": "超精细单元窑多孔拉丝制备单丝直径4-5微米开纤电子纱",
        "density_g_cm3": 2.36,
        "tensile_strength_cn_dtex": 11.5,
        "tensile_strength_gpa": 2.70,
        "tensile_modulus_gpa": 65.0,
        "elongation_at_break_pct": 3.8,
        "moisture_regain_pct": 0.0,
        "loi_pct": 100.0,
        "melting_point_c": 1250.0,
        "max_service_temp_c": 600.0,
        "typical_applications": "AI算力GPU服务器主板、5G-A/6G毫米波基站天线PCB板、自动驾驶毫米波雷达高频高速印制电路布",
        "representative_brands": "Low-Dk Glass, 巨石高频印制板基布",
        "tech_status_2026": "10 GHz下介电常数降至4.0以下且介质损耗角切正值<0.002，全面满足百Tbps吞吐算力集群极端低延迟信号传输",
        "is_bio_based": 0,
        "is_biodegradable": 0,
        "is_high_performance": 1,
        "aliases": [("Low-Dk玻纤", "abbreviation"), ("低介电玻璃纤维", "standard_name")],
        "standards": [("GB", "GB/T 18374-2008", "印制板用E玻璃纤维布")]
    },
    {
        "category_code": "INORG_GLASS",
        "code": "AR-GLASS",
        "name_zh": "耐碱玻璃纤维 (AR-玻纤/抗裂水泥抗碱纤维)",
        "name_en": "Alkali-Resistant Glass Fiber (AR-Glass)",
        "chemical_name": "含高浓度氧化锆耐碱硅酸盐玻璃 (ZrO2含量>16.7%)",
        "chemical_formula": "SiO2-ZrO2-Na2O system",
        "cas_number": "65997-17-3",
        "generation": "第2代建筑特种工程纤维",
        "discovery_year": "1960s",
        "commercial_year": "1971",
        "pioneering_entity": "BRE / Pilkington (皮尔金顿 Cem-FIL)",
        "spinning_method": "铂金坩埚或耐高温特种池窑拉丝",
        "density_g_cm3": 2.74,
        "tensile_strength_cn_dtex": 11.0,
        "tensile_strength_gpa": 3.0,
        "tensile_modulus_gpa": 72.0,
        "elongation_at_break_pct": 3.6,
        "moisture_regain_pct": 0.0,
        "loi_pct": 100.0,
        "melting_point_c": 1250.0,
        "max_service_temp_c": 600.0,
        "typical_applications": "玻璃纤维增强水泥外墙异形挂板(GRC幕墙)、公路桥梁防撞栏混凝土抗裂防渗筋、高耐久预制构件",
        "representative_brands": "Cem-FIL, 泰山耐碱玻纤",
        "tech_status_2026": "高含量氧化锆钝化膜技术在强碱性(pH>13)水泥水化环境下耐受寿命超50年，GRC建筑立面艺术造型全球标准材料",
        "is_bio_based": 0,
        "is_biodegradable": 0,
        "is_high_performance": 0,
        "aliases": [("AR玻纤", "abbreviation"), ("耐碱玻纤", "colloquial"), ("Cem-FIL", "trade_name")],
        "standards": [("GB", "GB/T 34676-2017", "耐碱玻璃纤维无捻粗纱")]
    },

    # ==================== 3. 天然矿物熔融纤维 (INORG_MINERAL) ====================
    {
        "category_code": "INORG_MINERAL",
        "code": "CBF",
        "name_zh": "玄武岩连续纤维 (CBF/天然火山岩纤维)",
        "name_en": "Continuous Basalt Fiber (CBF)",
        "chemical_name": "天然均质辉绿玄武岩矿石熔融铝硅铁钙无机聚合物",
        "chemical_formula": "SiO2-Al2O3-Fe2O3-FeO-CaO-MgO",
        "cas_number": "65997-17-3",
        "generation": "第3代天然无机绿色高性能纤维",
        "discovery_year": "1923",
        "commercial_year": "1985",
        "pioneering_entity": "前苏联乌克兰材料问题研究所 / 东南大学 / 四川航天拓鑫",
        "spinning_method": "天然火山玄武岩矿石破碎清洗后，经1450-1500℃纯熔融直接由铂铑合金漏板高速拉丝 (全过程无工业废水三废)",
        "density_g_cm3": 2.75,
        "tensile_strength_cn_dtex": 13.0,
        "tensile_strength_gpa": 3.60,
        "tensile_modulus_gpa": 95.0, # 模量与刚性显著优于E玻纤
        "elongation_at_break_pct": 3.1,
        "moisture_regain_pct": 0.1,
        "loi_pct": 100.0, # 天然不燃
        "melting_point_c": 1450.0,
        "max_service_temp_c": 650.0, # 瞬时耐温900℃，低温耐液氮-260℃
        "typical_applications": "海洋重腐蚀跨海大桥无锈耐腐蚀筋材(替代传统钢筋)、防火消防逃生毯与防火幕帘、沥青道路抗车辙网格布、高铁吸音屏障",
        "representative_brands": "Kamenny Vek, 四川拓鑫玄武岩纤维, 江苏天龙",
        "tech_status_2026": "百孔至千孔大型多排漏板自动化均质拉丝技术彻底攻克，能耗大幅下降，中国产能位居全球榜首",
        "is_bio_based": 0,
        "is_biodegradable": 0,
        "is_high_performance": 1,
        "aliases": [("玄武岩纤维", "colloquial"), ("火山岩纤维", "colloquial"), ("CBF", "abbreviation")],
        "standards": [("GB", "GB/T 25045-2010", "玄武岩纤维无捻粗纱"), ("ISO", "ISO 2076:2021", "Basalt generic name")]
    },

    # ==================== 4. 先进陶瓷连续纤维 (INORG_CERAMIC) ====================
    {
        "category_code": "INORG_CERAMIC",
        "code": "SIC-F",
        "name_zh": "连续碳化硅纤维 (SiC纤维 1代/2代/3代)",
        "name_en": "Continuous Silicon Carbide Fiber (SiC Fiber)",
        "chemical_name": "近化学计量比致密微晶碳化硅",
        "chemical_formula": "SiC (微量游离碳与氧化硅)",
        "cas_number": "409-21-2",
        "generation": "第4代超高温战略热结构陶瓷纤维",
        "discovery_year": "1975",
        "commercial_year": "1980s",
        "pioneering_entity": "Seishi Yajima (矢岛圣使 / 日本东北大学) / 日本碳素 (Nippon Carbon) / 国防科大",
        "spinning_method": "聚碳硅烷(PCS)前驱体熔融纺丝，经不熔化空气/电子束辐照交联后，在惰性气氛经1200-1800℃高温热解烧结",
        "density_g_cm3": 3.10,
        "tensile_strength_cn_dtex": 10.0,
        "tensile_strength_gpa": 3.0,
        "tensile_modulus_gpa": 400.0, # 第3代近化学计量比高纯SiC模量高达400 GPa
        "elongation_at_break_pct": 0.8,
        "moisture_regain_pct": 0.0,
        "loi_pct": 100.0,
        "melting_point_c": 2700.0, # 超高温分解
        "max_service_temp_c": 1400.0, # 在含氧环境下耐1400-1500℃超高温长时间服役
        "typical_applications": "新一代军民用航空涡轮发动机热端陶瓷基复合材料(CMC-SiC)导向叶片与转子、高超音速飞行器燃烧室喉道壁、核反应堆包壳管",
        "representative_brands": "Nicalon (1代), Hi-Nicalon (2代), Hi-Nicalon Type S (3代), Tyranno, 湖南赛菲",
        "tech_status_2026": "第3代耐温超1450℃超低氧耐蠕变近化学计量比SiC长丝百吨级产线稳定交付，支撑我国国产先进航空发动机商用试车",
        "is_bio_based": 0,
        "is_biodegradable": 0,
        "is_high_performance": 1,
        "aliases": [("碳化硅纤维", "colloquial"), ("SiC纤维", "abbreviation"), ("Nicalon", "trade_name")],
        "standards": [("GB", "GB/T 36765-2018", "碳化硅长丝"), ("ASTM", "ASTM C1557", "Standard Test Method for Tensile Strength of Ceramic Fibers")]
    },
    {
        "category_code": "INORG_CERAMIC",
        "code": "AL2O3-F",
        "name_zh": "连续氧化铝微晶纤维 (Nextel 610/720)",
        "name_en": "Continuous Alumina Ceramic Fiber",
        "chemical_name": "超细纳米晶α-Al2O3 / 莫来石复合多晶陶瓷",
        "chemical_formula": "Al2O3-SiO2 (>99% or Mullite composite)",
        "cas_number": "1344-28-1",
        "generation": "第4代超高温抗氧化陶瓷纤维",
        "discovery_year": "1970s",
        "commercial_year": "1990s",
        "pioneering_entity": "3M 公司 (Nextel 610 / 720) / 山东硅苑 / 浙江拓盛",
        "spinning_method": "溶胶-凝胶法 (Sol-Gel): 铝氧烷/铝盐水溶胶与微量助剂配置纺丝胶体，干法挤出纺丝并经1300℃受控快速烧结",
        "density_g_cm3": 3.90, # 高密度纯陶瓷
        "tensile_strength_cn_dtex": 8.0,
        "tensile_strength_gpa": 3.10,
        "tensile_modulus_gpa": 380.0,
        "elongation_at_break_pct": 0.8,
        "moisture_regain_pct": 0.0,
        "loi_pct": 100.0,
        "melting_point_c": 2050.0,
        "max_service_temp_c": 1200.0, # 纯氧化环境下终生不发生氧化（因本身为完全氧化物）
        "typical_applications": "航空发动机排气尾喷管高温隔热毯、特种高温陶瓷基刹车盘、空间碎片微流星体超高速撞击防护屏蔽网、金属基复合材料强化丝",
        "representative_brands": "Nextel 610, Nextel 720 (3M)",
        "tech_status_2026": "彻底解决微晶晶粒在1200℃以上长时服役晶粒粗化痛点，实现金属基/氧化物陶瓷基复合材料关键强化件量产",
        "is_bio_based": 0,
        "is_biodegradable": 0,
        "is_high_performance": 1,
        "aliases": [("氧化铝纤维", "colloquial"), ("Nextel", "trade_name"), ("刚玉纤维", "colloquial")],
        "standards": [("ASTM", "ASTM C1557", "Tensile Strength of Ambient Ceramic Fibers")]
    },
    {
        "category_code": "INORG_CERAMIC",
        "code": "SI3N4-F",
        "name_zh": "连续氮化硅纤维 (Si3N4纤维)",
        "name_en": "Continuous Silicon Nitride Fiber",
        "chemical_name": "多晶氮化硅结构陶瓷长丝",
        "chemical_formula": "Si3N4",
        "cas_number": "12033-89-5",
        "generation": "第4代超高温耐磨特种陶瓷纤维",
        "discovery_year": "1980s",
        "commercial_year": "2000s",
        "pioneering_entity": "Dow Corning / 日本东燃 (Tonen) / 中科院化学所",
        "spinning_method": "聚硅氮烷(Polysilazane)前驱体聚合熔融纺丝，氨气气氛下脱碳交联高温热解",
        "density_g_cm3": 2.50,
        "tensile_strength_cn_dtex": 10.5,
        "tensile_strength_gpa": 2.60,
        "tensile_modulus_gpa": 250.0,
        "elongation_at_break_pct": 1.0,
        "moisture_regain_pct": 0.0,
        "loi_pct": 100.0,
        "melting_point_c": 1900.0,
        "max_service_temp_c": 1300.0,
        "typical_applications": "超高超音速导弹天线罩耐冲刷透波复合材料、耐熔融金属浸润坩埚内衬、耐磨高温轴承增强件",
        "representative_brands": "Tonen Si3N4, 聚硅氮烷基氮化硅纤维",
        "tech_status_2026": "具有优于SiC的微波透波率与极佳抗熔融铝液铁水腐蚀性，在电磁窗口与特种冶金中实现列装应用",
        "is_bio_based": 0,
        "is_biodegradable": 0,
        "is_high_performance": 1,
        "aliases": [("氮化硅纤维", "colloquial"), ("Si3N4", "abbreviation")],
        "standards": [("ISO", "ISO 19634", "Fine ceramics - Ceramic composites at high temperature")]
    },
    {
        "category_code": "INORG_CERAMIC",
        "code": "BORON-F",
        "name_zh": "连续硼纤维 (Boron Fiber)",
        "name_en": "Continuous Boron Fiber",
        "chemical_name": "微晶元素硼在钨丝/碳丝基底上气相沉积包覆物",
        "chemical_formula": "B on W core / C core",
        "cas_number": "14798-12-0",
        "generation": "第2代超高刚度结构增强纤维",
        "discovery_year": "1959",
        "commercial_year": "1966",
        "pioneering_entity": "Claude Talley (Texaco / 特士古) / Specialty Materials Inc",
        "spinning_method": "化学气相沉积法 (CVD): 以12微米极细钨丝或碳丝为芯材通电红热(1200℃)，三氯化硼与氢气在反应室还原沉积硼",
        "density_g_cm3": 2.55,
        "tensile_strength_cn_dtex": 14.0,
        "tensile_strength_gpa": 3.60,
        "tensile_modulus_gpa": 400.0, # 直径较大(100-140微米)，抗压屈屈曲与刚度无与伦比
        "elongation_at_break_pct": 0.9,
        "moisture_regain_pct": 0.0,
        "loi_pct": 100.0,
        "melting_point_c": 2070.0,
        "max_service_temp_c": 500.0,
        "typical_applications": "F-15/F-14战机水平平尾主承力结构、B-1轰炸机机翼后梁、核反应堆中子吸收屏蔽网、顶级钓竿中段加劲丝",
        "representative_brands": "Specialty Materials Boron, Textron Boron",
        "tech_status_2026": "凭借超粗单丝直径带来的超强抗压缩与轴向承载力，在战斗机受损机体碳/硼复合补片微创原位修复中持续独占关键地位",
        "is_bio_based": 0,
        "is_biodegradable": 0,
        "is_high_performance": 1,
        "aliases": [("硼纤维", "colloquial"), ("CVD硼纤维", "standard_name")],
        "standards": [("ASTM", "ASTM D3379", "Tensile Strength and Young's Modulus for High-Modulus Single-Filament Materials")]
    },

    # ==================== 5. 金属与液态金属微丝纤维 (INORG_METAL) ====================
    {
        "category_code": "INORG_METAL",
        "code": "SS-F",
        "name_zh": "不锈钢超细微丝纤维 (金属纤维)",
        "name_en": "Stainless Steel Microfiber (Metal Fiber)",
        "chemical_name": "奥氏体316L微合金不锈钢",
        "chemical_formula": "Fe-Cr-Ni-Mo (316L)",
        "cas_number": "65997-19-5",
        "generation": "第2代特种多功能导电纤维",
        "discovery_year": "1960s",
        "commercial_year": "1970s",
        "pioneering_entity": "Bekaert (比利时贝卡尔特 Bekinox) / 西部材料",
        "spinning_method": "集束拉拔法 (Bundle Drawing): 上千根不锈钢丝包覆于软钢基体中多道次冷拉拔减径至1-8微米后酸洗溶去基体",
        "density_g_cm3": 7.90, # 金属高密度
        "tensile_strength_cn_dtex": 1.5,
        "tensile_strength_gpa": 1.20,
        "tensile_modulus_gpa": 200.0,
        "elongation_at_break_pct": 2.0,
        "moisture_regain_pct": 0.0,
        "loi_pct": 100.0,
        "melting_point_c": 1400.0,
        "max_service_temp_c": 600.0,
        "typical_applications": "军工防电磁辐射服织物、触摸屏手套导电指尖指头纱、汽车挡风玻璃热弯耐高温缓冲织物、防静电洁净室工装",
        "representative_brands": "Bekinox (贝卡尔特), Bekaert Beki-sheld, 西部材料金属纤维",
        "tech_status_2026": "单丝直径突破1微米极限并能与棉、涤纶等任意混纺成高支纱线，成为智能穿戴柔性电极不可磨损的高可靠金属导体",
        "is_bio_based": 0,
        "is_biodegradable": 0,
        "is_high_performance": 1,
        "aliases": [("不锈钢纤维", "colloquial"), ("金属纤维", "standard_name"), ("Bekinox", "trade_name"), ("ME", "iso_code")],
        "standards": [("GB", "GB/T 4146.1-2020", "金属纤维"), ("ISO", "ISO 2076:2021", "Metal fibre")]
    },
    {
        "category_code": "INORG_METAL",
        "code": "LM-F",
        "name_zh": "镓铟液态合金柔性同轴拉伸纤维 (液态金属纤维)",
        "name_en": "Liquid Metal Coaxial Stretchable Fiber (EGaIn Fiber)",
        "chemical_name": "共晶镓铟合金核/弹性硅胶-聚氨酯壳层",
        "chemical_formula": "EGaIn core (75.5% Ga, 24.5% In) / Elastomer shell",
        "cas_number": None,
        "generation": "第4代室温流态高导电智能纤维",
        "discovery_year": "2010s",
        "commercial_year": "2022",
        "pioneering_entity": "Dickey (北卡州立大学) / 刘静 (清华大学/理化所)",
        "spinning_method": "同轴微流控共挤出纺丝 (外层聚合弹性体原位光固化，内芯连续注入室温液态金属)",
        "density_g_cm3": 2.10,
        "tensile_strength_cn_dtex": 0.8,
        "tensile_strength_gpa": 0.08,
        "tensile_modulus_gpa": 0.02,
        "elongation_at_break_pct": 700.0, # 超大拉伸下导电性不中断
        "moisture_regain_pct": 0.0,
        "loi_pct": 28.0,
        "melting_point_c": 15.5, # 内部金属在室温保持液态
        "max_service_temp_c": 120.0,
        "typical_applications": "大幅拉伸变形下电阻近乎零变化的超弹柔性天线、可水洗智能织物心电ECG传感导线、软体机器人人工肌肉驱动线",
        "representative_brands": "LiquidConduct, EGaIn Fiber",
        "tech_status_2026": "解决严苛剪切破裂下自愈合封装难题，在万次700%超大拉伸循环下电阻变化率小于5%，进入智能运动医疗量产",
        "is_bio_based": 0,
        "is_biodegradable": 0,
        "is_high_performance": 1,
        "aliases": [("液态金属纤维", "colloquial"), ("镓铟合金丝", "colloquial"), ("EGaIn", "abbreviation")],
        "standards": [("IEEE", "IEEE P2844", "Standard for Recommended Practice of Flexible and Stretchable Electronics")]
    },

    # ==================== 6. 前沿智能、仿生与生物工程纤维 (EMERGING 2026) ====================
    {
        "category_code": "EMG_BIOENG",
        "code": "SPIDER-F",
        "name_zh": "重组基因工程蜘蛛丝纤维 (人造蜘蛛丝)",
        "name_en": "Recombinant Spider Silk Protein Fiber",
        "chemical_name": "基因工程大肠杆菌/酵母重组大壶状腺蛛丝蛋白 (MaSp1/MaSp2)",
        "chemical_formula": "Recombinant Spidroin Polypeptide",
        "cas_number": None,
        "generation": "第4代合成生物学革命性仿生纤维",
        "discovery_year": "1990s",
        "commercial_year": "2019",
        "pioneering_entity": "Spiber (日本) / AMSilk (德国) / 聚维元创 / 态创生物",
        "spinning_method": "发酵工程菌超高密度发酵合成重组蛛丝蛋白，微流控模拟蜘蛛纺丝管进行水相剪切拉伸结晶成纤",
        "density_g_cm3": 1.32,
        "tensile_strength_cn_dtex": 8.5,
        "tensile_strength_gpa": 1.15,
        "tensile_modulus_gpa": 15.0,
        "elongation_at_break_pct": 35.0, # 综合强韧性(断裂能)超越凯夫拉和钢丝
        "moisture_regain_pct": 10.0,
        "loi_pct": 24.0,
        "melting_point_c": None,
        "max_service_temp_c": 150.0,
        "typical_applications": "奢华户外极地探索冲锋衣(Moon Parka)、可吸收无异物感神经外科精密缝线、环保超韧防震汽车保险杠复合增强织物",
        "representative_brands": "Brewed Protein (Spiber), Biosteel (AMSilk), QMONOS",
        "tech_status_2026": "百吨级工业化生物合成发酵工厂满产，成本由每公斤上万美元大幅降至百美元区间，全生物相容完全降解",
        "is_bio_based": 1,
        "is_biodegradable": 1,
        "is_high_performance": 1,
        "aliases": [("人造蜘蛛丝", "colloquial"), ("蜘蛛丝纤维", "colloquial"), ("Brewed Protein", "trade_name"), ("Biosteel", "trade_name")],
        "standards": [("ASTM", "ASTM F3160", "Characterization of Recombinant Structural Proteins")]
    },
    {
        "category_code": "EMG_AERO",
        "code": "AERO-F",
        "name_zh": "仿北极熊毛纳微多孔气凝胶超保暖纤维",
        "name_en": "Biomimetic Aerogel Textile Fiber",
        "chemical_name": "仿北极熊毛芯-壳结构微孔二氧化硅-高分子纳米气凝胶复合长丝",
        "chemical_formula": "Silica/Polymer Core-Sheath Nanoporous Network",
        "cas_number": None,
        "generation": "第4代极端热防护仿生织物纤维",
        "discovery_year": "2018",
        "commercial_year": "2023",
        "pioneering_entity": "柏浩 (浙江大学化工学院团队原创发明)",
        "spinning_method": "定向冻结冷冻纺丝结合超临界CO2干燥，并在外层原位共挤包覆坚韧透明聚酯/聚氨酯保护鞘层",
        "density_g_cm3": 0.25, # 极低密度，超高孔隙率(>90%)
        "tensile_strength_cn_dtex": 3.8,
        "tensile_strength_gpa": 0.10,
        "tensile_modulus_gpa": 1.2,
        "elongation_at_break_pct": 16.0,
        "moisture_regain_pct": 1.5,
        "loi_pct": 32.0,
        "melting_point_c": 220.0,
        "max_service_temp_c": 160.0,
        "typical_applications": "零下40℃极地超薄羽绒替代保暖服、航天员出舱服保暖层、冷链物流超薄隔热垫、红外热隐身伪装迷彩服",
        "representative_brands": "PolarAerogel, 仿生极地绒",
        "tech_status_2026": "完全解决传统气凝胶易脆碎掉粉难题，仅数毫米厚度即可达到传统厚重羽绒服同等保暖效果，耐洗涤超50次",
        "is_bio_based": 0,
        "is_biodegradable": 0,
        "is_high_performance": 1,
        "aliases": [("气凝胶纤维", "colloquial"), ("北极熊毛纤维", "colloquial"), ("极寒纤维", "colloquial")],
        "standards": [("GB", "GB/T 39548-2020", "气凝胶绝热材料技术条件")]
    },
    {
        "category_code": "EMG_2D",
        "code": "MXENE-F",
        "name_zh": "MXene二维过渡金属碳化物智能导电纤维",
        "name_en": "MXene Multifunctional Smart Fiber",
        "chemical_name": "二维碳化钛 (Ti3C2Tx) 纳米多层叠合长丝",
        "chemical_formula": "Ti3C2Tx (Tx = -OH, -F, =O)",
        "cas_number": "12363-89-2",
        "generation": "第4代超高电导率二维晶体纳米纤维",
        "discovery_year": "2011",
        "commercial_year": "2022",
        "pioneering_entity": "Yury Gogotsi / 德雷塞尔大学 / 北京化工大学 / 复旦大学",
        "spinning_method": "无表面活性剂大单片无缺陷Ti3C2Tx液晶相水溶液直接湿法挤出微流控纺丝",
        "density_g_cm3": 3.20,
        "tensile_strength_cn_dtex": 4.5,
        "tensile_strength_gpa": 0.65,
        "tensile_modulus_gpa": 55.0,
        "elongation_at_break_pct": 3.0,
        "moisture_regain_pct": 0.5,
        "loi_pct": 35.0,
        "melting_point_c": None,
        "max_service_temp_c": 200.0,
        "typical_applications": "超薄轻量化宽频电磁屏蔽织物(屏蔽效能>80 dB)、高灵敏呼气微湿度探测纤维、极端快速电热变温服、超级电容器储能电极",
        "representative_brands": "MXeneFil, 钛碳烯纤维",
        "tech_status_2026": "通过化学配位与表面聚合物分子级抗氧化包覆，彻底攻克水氧环境下易氧化降解难题，电导率稳定在1.2×10^6 S/m",
        "is_bio_based": 0,
        "is_biodegradable": 0,
        "is_high_performance": 1,
        "aliases": [("MXene纤维", "colloquial"), ("碳化钛纤维", "chemical_name")],
        "standards": [("IEEE", "IEEE Std 2844.1", "Standard for 2D Materials Characterization in Wearables")]
    },
    {
        "category_code": "EMG_ENERGY",
        "code": "FIBER-LIB",
        "name_zh": "全柔性纤维状锂离子储能电池",
        "name_en": "Fiber-shaped Lithium-ion Battery (Fiber-LIB)",
        "chemical_name": "同轴准固态正负极活性材料与凝胶电解质同轴连续纤维",
        "chemical_formula": "LiFePO4/Gel-Polymer/LTO-CNT coaxial assembly",
        "cas_number": None,
        "generation": "第4代穿戴式本体储能革命性器件",
        "discovery_year": "2014",
        "commercial_year": "2023",
        "pioneering_entity": "彭慧胜 (复旦大学高分子科学系院士团队原创发明)",
        "spinning_method": "连续多层流挤出包覆同轴纺丝工艺，原位紫外光固化高离子电导率凝胶聚合物电解质",
        "density_g_cm3": 1.85,
        "tensile_strength_cn_dtex": 1.2,
        "tensile_strength_gpa": 0.15,
        "tensile_modulus_gpa": 2.5,
        "elongation_at_break_pct": 15.0,
        "moisture_regain_pct": 0.0,
        "loi_pct": 30.0, # 准固态难燃，剪切穿刺不发火爆炸
        "melting_point_c": None,
        "max_service_temp_c": 80.0,
        "typical_applications": "织物级隐形储能电源(一件普通编织发热衣可连续为手机无线充电4小时)、消防智能搜救服中枢能源、植入微型医疗设备供电",
        "representative_brands": "FiberBatt, 彭慧胜团队纤维电池",
        "tech_status_2026": "实现百米级全自动连续编织与工业织机无损走纱，能量密度突破100 Wh/kg，经受万次弯折与强力水洗容量保持率>90%",
        "is_bio_based": 0,
        "is_biodegradable": 0,
        "is_high_performance": 1,
        "aliases": [("纤维电池", "colloquial"), ("电池纤维", "colloquial"), ("储能纤维", "colloquial")],
        "standards": [("GB", "GB/T 38331-2019", "可穿戴电子产品 软质储能器件通用要求")]
    },
    {
        "category_code": "EMG_ENERGY",
        "code": "TENG-F",
        "name_zh": "织物摩擦纳米发电机纤维 (TENG人体动能捕获纤维)",
        "name_en": "Triboelectric Nanogenerator Fiber",
        "chemical_name": "微结构全氟乙丙烯/硅橡胶/银导电微核共挤弹性纤维",
        "chemical_formula": "FEP-PDMS/Ag-conductive core",
        "cas_number": None,
        "generation": "第4代环境自驱动能源纤维",
        "discovery_year": "2012",
        "commercial_year": "2022",
        "pioneering_entity": "王中林 (佐治亚理工 / 中科院纳米能源所)",
        "spinning_method": "微纳复合成型与同轴熔融纺丝，表面激光微纳阵列织构化处理增大接触带电面积",
        "density_g_cm3": 1.35,
        "tensile_strength_cn_dtex": 2.2,
        "tensile_strength_gpa": 0.25,
        "tensile_modulus_gpa": 1.5,
        "elongation_at_break_pct": 40.0,
        "moisture_regain_pct": 0.1,
        "loi_pct": 32.0,
        "melting_point_c": 190.0,
        "max_service_temp_c": 110.0,
        "typical_applications": "自供电运动鞋垫与步态监测衣、落雨水滴能量收集伞面、无需外接电池的永久免充电无线SOS定位发报夹克",
        "representative_brands": "NanoTENG Fiber, 纳米能源所自驱动织物",
        "tech_status_2026": "瞬时输出功率密度达到50 W/m²，日常行走摆臂产生的电能可直接点亮数百颗LED并持续驱动蓝牙数据传输芯片",
        "is_bio_based": 0,
        "is_biodegradable": 0,
        "is_high_performance": 1,
        "aliases": [("TENG纤维", "abbreviation"), ("摩擦发电纤维", "colloquial"), ("自驱动纤维", "colloquial")],
        "standards": [("IEEE", "IEEE 3105", "Standard for Triboelectric Nanogenerators")]
    },
    {
        "category_code": "EMG_SMART",
        "code": "PCM-F",
        "name_zh": "微胶囊相变智能调温纤维 (Outlast双向恒温纤维)",
        "name_en": "Phase Change Material Fiber (PCM Fiber)",
        "chemical_name": "包覆高级烷烃微胶囊共混聚酯或腈纶",
        "chemical_formula": "Polymer matrix with n-octadecane microcapsules",
        "cas_number": None,
        "generation": "第3代自适应智能恒温舒适纤维",
        "discovery_year": "1980s",
        "commercial_year": "1997",
        "pioneering_entity": "NASA 宇航服宇航温控研究 / Outlast Technologies",
        "spinning_method": "湿法或熔融纺丝 (将高焓值相变石蜡微胶囊高度分散均匀注入高聚物基体中)",
        "density_g_cm3": 1.25,
        "tensile_strength_cn_dtex": 3.0,
        "tensile_strength_gpa": 0.36,
        "tensile_modulus_gpa": 4.5,
        "elongation_at_break_pct": 28.0,
        "moisture_regain_pct": 1.2,
        "loi_pct": 21.0,
        "melting_point_c": 220.0, # 基体熔点，微胶囊在28-32℃发生固-液相变潜热吸放热
        "max_service_temp_c": 120.0,
        "typical_applications": "宇航员宇航服手套内衬、高级四季恒温羽绒被、高热负荷电竞椅垫、户外骤冷骤热运动冲锋衣中层",
        "representative_brands": "Outlast (奥特莱斯), 恒温天丝, 溢达PCM微胶囊纤维",
        "tech_status_2026": "纳米无缝二氧化硅壁材微胶囊实现耐受普通机洗100次无渗漏，相变潜热焓值突破80 J/g，实现人体体表微气候±2℃动态自稳定",
        "is_bio_based": 0,
        "is_biodegradable": 0,
        "is_high_performance": 0,
        "aliases": [("相变纤维", "colloquial"), ("恒温纤维", "colloquial"), ("Outlast", "trade_name"), ("PCM纤维", "abbreviation")],
        "standards": [("GB", "FZ/T 52044-2017", "相变调温粘胶短纤维"), ("ASTM", "ASTM D7024", "Steady State and Dynamic Thermal Performance of Textiles")]
    },
    {
        "category_code": "EMG_SMART",
        "code": "SMP-F",
        "name_zh": "温敏与力敏形状记忆聚合物自适应透气纤维",
        "name_en": "Shape Memory Polymer Adaptive Fiber",
        "chemical_name": "热致/湿致形状记忆嵌段共聚聚氨酯",
        "chemical_formula": "Segmented Polyurethane with reversible crystalline switches",
        "cas_number": None,
        "generation": "第4代仿生动态呼吸智能纤维",
        "discovery_year": "1990s",
        "commercial_year": "2015",
        "pioneering_entity": "Mitsubishi Heavy Industries (三菱重工 DiAPLEX) / 香港理工大学",
        "spinning_method": "干湿法微孔纺丝，精确调控聚合物微相分离可逆相转变温度(Tg/Tm设定在体温34-37℃)",
        "density_g_cm3": 1.19,
        "tensile_strength_cn_dtex": 2.8,
        "tensile_strength_gpa": 0.32,
        "tensile_modulus_gpa": 1.8,
        "elongation_at_break_pct": 200.0,
        "moisture_regain_pct": 2.0,
        "loi_pct": 22.0,
        "melting_point_c": 180.0,
        "max_service_temp_c": 110.0,
        "typical_applications": "出汗发热时微孔自动扩张‘呼气’排热、降温静止时微孔自动收缩‘吸气’保暖的智能变孔隙运动织物、防烫伤自膨胀防护服",
        "representative_brands": "DiAPLEX (透湿记忆薄膜与纤维), MemoryTex",
        "tech_status_2026": "响应时间缩短至秒级，可逆孔隙开合率提升至40%，成为高端滑雪服与特种极限战备服自适应环境调控核心黑科技",
        "is_bio_based": 0,
        "is_biodegradable": 0,
        "is_high_performance": 0,
        "aliases": [("形状记忆纤维", "colloquial"), ("呼吸纤维", "colloquial"), ("SMP纤维", "abbreviation")],
        "standards": [("GB", "GB/T 39547-2020", "形状记忆高分子材料性能测试方法")]
    },
    {
        "category_code": "EMG_SMART",
        "code": "FIBER-DISP",
        "name_zh": "大面积全柔性纤维电致发光与显示器件",
        "name_en": "Electro-luminescent Display & Light-Emitting Fiber",
        "chemical_name": "同轴发光层(发光高分子/钙钛矿)/透明导电聚合物电极织物纤维",
        "chemical_formula": "Conductive Core / PLED or Perovskite / Transparent Sheath",
        "cas_number": None,
        "generation": "第4代信息交互概念级发光显示纤维",
        "discovery_year": "2015",
        "commercial_year": "2024",
        "pioneering_entity": "彭慧胜 (复旦大学团队发光织物) / 韩国科学技术院 (KAIST)",
        "spinning_method": "同轴复合溶液精密涂覆与微流控挤出，形成经纬交织发光微像素点阵",
        "density_g_cm3": 1.45,
        "tensile_strength_cn_dtex": 2.0,
        "tensile_strength_gpa": 0.26,
        "tensile_modulus_gpa": 3.0,
        "elongation_at_break_pct": 20.0,
        "moisture_regain_pct": 0.0,
        "loi_pct": 24.0,
        "melting_point_c": 200.0,
        "max_service_temp_c": 90.0,
        "typical_applications": "衣服表面全彩动态地图导航显示、聋哑人士手势手套触控发光转文字衣、夜间交警及施工人员全自发光安全警示服",
        "representative_brands": "LumiTextile, DisplayFiber",
        "tech_status_2026": "发光亮度突破1000 cd/m²，功耗小于瓦特级，耐折叠耐水洗达30次，实现衣物与智能手机蓝牙连接直接推送显示即时通知",
        "is_bio_based": 0,
        "is_biodegradable": 0,
        "is_high_performance": 1,
        "aliases": [("发光纤维", "colloquial"), ("显示纤维", "colloquial"), ("发光织物", "colloquial")],
        "standards": [("IEC", "IEC 63203-204-1", "Wearable electronic devices and technologies - Electronic textile display")]
    }
]

print(f"Loaded Part 3: {len(FIBERS_PART_3)} chemical fibers.")
